'use strict';
// Automatic settings backups (1.2.0). Before an app update is installed (while the app closes), the app's saved
// settings folder is copied to settings-backups/ inside it: accounts (still encrypted by Windows for this user), relay
// servers, workspace layout, OBS link, Stream Deck pairing, Stream Assist settings. Chromium's caches and logs are
// left out. The last 5 backups are kept. A restore is done at the next start, before anything is loaded, and the
// current settings are backed up first so a restore can be undone. Each top-level item is replaced as a whole, so
// browser storage databases (Local Storage, IndexedDB) are never mixed between versions.
const fs = require('node:fs'),
  path = require('node:path');

const DIR = 'settings-backups',
  KEEP = 5,
  MAX_FILE = 50 * 1024 * 1024,
  MAX_TOTAL = 500 * 1024 * 1024;
// Regenerated by Chromium or not settings.
const SKIP = new Set([
  DIR,
  'app-update',
  'Cache',
  'Code Cache',
  'GPUCache',
  'DawnCache',
  'DawnGraphiteCache',
  'DawnWebGPUCache',
  'GrShaderCache',
  'GraphiteDawnCache',
  'ShaderCache',
  'Crashpad',
  'blob_storage',
  'Service Worker',
  'Shared Dictionary',
  'SingletonLock',
  'SingletonCookie',
  'SingletonSocket',
  'lockfile'
]);
// App logs sit at the top of the folder. Inside browser storage folders, *.log files are the database's own
// journal (the newest settings), so they are kept.
const skipFile = (name, top) => name === 'LOCK' || (top && /\.log$/i.test(name)) || /\.tmp$/i.test(name);

function walk(root, rel = '') {
  const out = [];
  for (const d of fs.readdirSync(path.join(root, rel), { withFileTypes: true })) {
    const name = rel ? rel + '/' + d.name : d.name;
    if (!rel && SKIP.has(d.name)) continue;
    if (d.isDirectory()) out.push(...walk(root, name));
    else if (d.isFile() && !skipFile(d.name, !rel)) out.push(name);
  }
  return out;
}

exports.create = userData => {
  const base = path.join(userData, DIR),
    pending = path.join(base, 'restore.json');

  function list() {
    let names = [];
    try {
      names = fs.readdirSync(base, { withFileTypes: true }).filter(d => d.isDirectory());
    } catch {}
    return names
      .map(d => {
        try {
          return {
            id: d.name,
            ...JSON.parse(fs.readFileSync(path.join(base, d.name, 'backup.json'), 'utf8'))
          };
        } catch {
          return null;
        }
      })
      .filter(Boolean)
      .sort((a, b) => b.at - a.at);
  }

  // Copies the settings folder; returns the backup id, or null when there is nothing to back up.
  // `protect` is never removed by the "keep the last 5" clean-up (the backup being restored).
  function snapshot(label, extra = {}, protect = '') {
    if (!fs.existsSync(userData)) return null;
    const files = walk(userData);
    if (!files.length) return null;
    const at = Date.now();
    const id =
      new Date(at).toISOString().replace(/[:.]/g, '-') + '-' + Math.random().toString(36).slice(2, 6);
    const dest = path.join(base, id);
    let total = 0,
      skipped = 0;
    fs.mkdirSync(dest, { recursive: true });
    for (const f of files) {
      try {
        const size = fs.statSync(path.join(userData, f)).size;
        if (size > MAX_FILE || total + size > MAX_TOTAL) {
          skipped++;
          continue;
        }
        fs.mkdirSync(path.dirname(path.join(dest, f)), { recursive: true });
        fs.copyFileSync(path.join(userData, f), path.join(dest, f));
        total += size;
      } catch {
        // A file in use (e.g. a browser storage lock) is left out.
        skipped++;
      }
    }
    // Written last: a backup without backup.json is incomplete and never listed or restored.
    fs.writeFileSync(
      path.join(dest, 'backup.json'),
      JSON.stringify({ label, at, bytes: total, skipped, ...extra })
    );
    for (const old of list()
      .filter(x => x.id !== protect)
      .slice(KEEP))
      fs.rmSync(path.join(base, old.id), { recursive: true, force: true });
    return id;
  }

  function requestRestore(id) {
    const b = list().find(x => x.id === id);
    if (!b) throw Error('That settings backup no longer exists.');
    fs.writeFileSync(pending, JSON.stringify({ id }));
    return b;
  }

  // At start, before settings are read: restores a requested backup. Returns the backup restored, or null.
  function applyPendingRestore() {
    let id;
    try {
      id = JSON.parse(fs.readFileSync(pending, 'utf8')).id;
    } catch {
      return null;
    }
    fs.rmSync(pending, { force: true });
    const b = list().find(x => x.id === id);
    if (!b || !/^[\w-]+$/.test(id)) return null;
    const src = path.join(base, id);
    snapshot('Before restoring the backup from ' + new Date(b.at).toLocaleString(), { undo: id }, id);
    for (const d of fs.readdirSync(src, { withFileTypes: true })) {
      if (d.name === 'backup.json') continue;
      const to = path.join(userData, d.name);
      fs.rmSync(to, { recursive: true, force: true });
      fs.cpSync(path.join(src, d.name), to, { recursive: true });
    }
    return b;
  }

  return { list, snapshot, requestRestore, applyPendingRestore };
};
