using System;using System.Drawing;using System.IO;using System.Threading;using System.Threading.Tasks;using System.Windows.Forms;

public partial class MainWindow {

 readonly System.Collections.Concurrent.ConcurrentDictionary<string,string> connectedAccounts=new System.Collections.Concurrent.ConcurrentDictionary<string,string>();

 string AccountIdentity(string name){string value;if(connectedAccounts.TryGetValue(name,out value)&&value!="")return value;return name=="Streamlabs"?"Socket token · Account name not provided":name=="Kick"?"Account not identified yet":"No account identified";}

 void ClearIdentity(string name){string old;connectedAccounts.TryRemove(name,out old);}



 CancellationTokenSource streamlabsStop,youtubeStop,kickStop;Task streamlabsTask,youtubeTask,kickTask;string streamlabsStatus="Streamlabs: not connected",youtubeStatus="YouTube: not connected",kickStatus="Kick: receiver setup needed";

 async Task ToggleStreamlabs(){if(streamlabsStop!=null){streamlabsStop.Cancel();return;}string token=AccountStore.Read<string>("streamlabs");if(string.IsNullOrWhiteSpace(token)){MessageBox.Show(this,"Open Accounts > Streamlabs > Set token first.");return;}var cancel=streamlabsStop=new CancellationTokenSource();try{var client=new DirectStreamlabs(s=>{if(!IsDisposed)streamlabsStatus=s;},a=>{if(!IsDisposed)Add(a);});streamlabsTask=client.Run(token,cancel.Token);await streamlabsTask;}catch(Exception){streamlabsStatus="Streamlabs: could not connect. Check account settings.";}finally{if(cancel.IsCancellationRequested)streamlabsStatus="Streamlabs: disconnected";streamlabsStop=null;cancel.Dispose();}}

 async Task ToggleYouTube(){if(youtubeStop!=null){youtubeStop.Cancel();return;}var config=AccountStore.Read<GoogleClient>("google-client");if(config==null){MessageBox.Show(this,"Open Accounts > YouTube > Import Google file first.");return;}var cancel=youtubeStop=new CancellationTokenSource();try{using(var client=new DirectYouTube(config,s=>{if(!IsDisposed)youtubeStatus=s;},a=>{if(!IsDisposed)Add(a);},name=>connectedAccounts["YouTube"]=name)) {youtubeTask=client.Run(cancel.Token);await youtubeTask;}}finally{youtubeStop=null;cancel.Dispose();}}

 async Task ToggleKick(){if(kickStop!=null){kickStop.Cancel();return;}var config=AccountStore.Read<KickSettings>("kick");if(config==null){MessageBox.Show(this,"Open Accounts > Kick > Receiver settings first.");return;}var cancel=kickStop=new CancellationTokenSource();try{using(var client=new DirectKick(config,s=>{if(!IsDisposed)kickStatus=s;},a=>{if(!IsDisposed)Add(a);},name=>connectedAccounts["Kick"]=name)) {kickTask=client.Run(cancel.Token);await kickTask;}}finally{kickStop=null;cancel.Dispose();}}

 void SetStreamlabs(){if(streamlabsStop!=null){MessageBox.Show(this,"Disconnect Streamlabs before replacing its token.");return;}using(var w=new Form{Text="Streamlabs token",Size=new Size(700,320),StartPosition=FormStartPosition.CenterParent,BackColor=Theme.Canvas,ForeColor=Theme.Text,Font=Font}){var text=new Label{Text="Copy your Socket API token from Streamlabs > Settings > API Settings > API Tokens. Paste it below. It stays protected on this Windows account.",Location=new Point(24,24),Size=new Size(630,80)};var entry=new TextBox{UseSystemPasswordChar=true,Location=new Point(24,115),Width=620};var save=Button("Save token",delegate{try{string value=entry.Text.Trim();if(value.Length<16||value.Length>4096||value.Contains(" "))throw new ArgumentException("Paste the complete Socket API token.");AccountStore.Save("streamlabs",value);w.Close();}catch(Exception){MessageBox.Show(w,"Could not save the token securely. Check the token and Windows profile access.");}},true);save.Location=new Point(24,170);w.Controls.AddRange(new Control[]{text,entry,save});w.ShowDialog(this);}}

 void ImportGoogle(){if(youtubeStop!=null){MessageBox.Show(this,"Disconnect YouTube before importing credentials.");return;}using(var picker=new OpenFileDialog{Title="Choose Google Desktop app credentials",Filter="Google credentials JSON|*.json",CheckFileExists=true})if(picker.ShowDialog(this)==DialogResult.OK)try{if(new FileInfo(picker.FileName).Length>65536)throw new ArgumentException();var config=GoogleClient.Parse(File.ReadAllText(picker.FileName));AccountStore.Save("google-client",config);AccountStore.Forget("youtube");youtubeStatus="YouTube: ready to sign in";MessageBox.Show(this,"Google credentials imported. Click Connect YouTube.");}catch(Exception){MessageBox.Show(this,"Could not import this file. Choose the JSON downloaded for a Google Desktop app and check Windows profile access.");}}

 void SetKick(){if(kickStop!=null){MessageBox.Show(this,"Disconnect Kick before changing its receiver.");return;}using(var w=new Form{Text="Kick receiver",Size=new Size(710,380),StartPosition=FormStartPosition.CenterParent,BackColor=Theme.Canvas,ForeColor=Theme.Text,Font=Font}){var saved=AccountStore.Read<KickSettings>("kick");var url=new TextBox{Text=saved==null?"https://assist.universalcollab.stream":saved.Url,Location=new Point(24,110),Width=640};var key=new TextBox{UseSystemPasswordChar=true,Location=new Point(24,190),Width=640};w.Controls.Add(new Label{Text="After deploying your Cloudflare receiver, enter its address and private receiver key. This is not your Kick client secret.",Location=new Point(24,20),Size=new Size(640,70)});w.Controls.Add(url);w.Controls.Add(new Label{Text="Receiver key",Location=new Point(24,155),AutoSize=true});w.Controls.Add(key);var save=Button("Save receiver",delegate{try{Uri uri;if(!Uri.TryCreate(url.Text.Trim(),UriKind.Absolute,out uri)||uri.Scheme!="https"||!uri.IsDefaultPort||uri.UserInfo!=""||uri.AbsolutePath!="/"||uri.Query!=""||uri.Fragment!="")throw new ArgumentException();string secret=key.Text.Trim();if(secret==""&&saved!=null)secret=saved.Key;if(secret.Length<32)throw new ArgumentException();AccountStore.Save("kick",new KickSettings{Url=uri.GetLeftPart(UriPartial.Authority),Key=secret});w.Close();}catch(Exception){MessageBox.Show(w,"Enter an HTTPS receiver address and a receiver key of at least 32 characters. The key is saved using Windows protection.");}},true);save.Location=new Point(24,245);w.Controls.Add(save);w.ShowDialog(this);}}

 async Task Forget(string name){try{if(name=="streamlabs"&&streamlabsStop!=null){streamlabsStop.Cancel();await streamlabsTask;}if(name=="youtube"&&youtubeStop!=null){youtubeStop.Cancel();await youtubeTask;}if(name=="kick"&&kickStop!=null){kickStop.Cancel();await kickTask;}AccountStore.Forget(name);ClearIdentity(name=="youtube"?"YouTube":name=="kick"?"Kick":"Streamlabs");if(name=="youtube")youtubeStatus="YouTube: signed out";if(name=="kick")kickStatus="Kick: signed out on this PC";if(name=="streamlabs")streamlabsStatus="Streamlabs: signed out";MessageBox.Show(this,"Saved connection removed from this PC. You can revoke app access on the service's account settings page.");}catch(Exception){MessageBox.Show(this,"Could not remove the saved connection. Disconnect and try again.");}}


 Button AccountConnectButton(Func<string> label,Func<Task> toggle){
  var button=Button(label(),async delegate{try{await toggle();}catch(Exception){MessageBox.Show(Form.ActiveForm??this,"Could not complete the connection. Check the account status and try again.");}},true);
  var timer=new System.Windows.Forms.Timer{Interval=400};
  timer.Tick+=delegate{button.Text=label();};
  button.Disposed+=delegate{timer.Dispose();};
  timer.Start();return button;
 }

 void ShowAccounts(string selected=null){using(var w=new Form{Text="Your accounts",Size=new Size(780,470),MinimumSize=new Size(740,450),StartPosition=FormStartPosition.CenterParent,BackColor=Theme.Canvas,ForeColor=Theme.Text,Font=Font}){var tabs=new TabControl{Dock=DockStyle.Fill,Padding=new Point(16,10)};w.Controls.Add(tabs);Action<string,string,Func<string>,Action<FlowLayoutPanel>> page=delegate(string name,string description,Func<string> state,Action<FlowLayoutPanel> actions){var tab=new TabPage(name){BackColor=Theme.Canvas,ForeColor=Theme.Text,Padding=new Padding(24)};tabs.TabPages.Add(tab);var layout=new FlowLayoutPanel{Dock=DockStyle.Fill,FlowDirection=FlowDirection.TopDown,WrapContents=false};tab.Controls.Add(layout);layout.Controls.Add(new Label{Text=description,Size=new Size(650,105)});var statusLabel=new Label{Text=AccountIdentity(name)+"\n"+state(),ForeColor=Theme.Accent,Size=new Size(650,75)};layout.Controls.Add(statusLabel);var timer=new System.Windows.Forms.Timer{Interval=400};timer.Tick+=delegate{statusLabel.Text=AccountIdentity(name)+"\n"+state();};timer.Start();tab.Disposed+=delegate{timer.Dispose();};var row=new FlowLayoutPanel{Size=new Size(650,105)};layout.Controls.Add(row);actions(row);};

 page("Twitch","Receive chat, follows, subscriptions, gifts, bits and raids directly. Sign in using your broadcaster account.",()=>twitchStatus,row=>{row.Controls.Add(AccountConnectButton(()=>twitchStop==null?"Connect Twitch":"Pause connection",ToggleTwitch));row.Controls.Add(Button("Sign out",async delegate{if(twitchStop!=null){twitchStop.Cancel();await twitchTask;}try{TwitchVault.Forget();ClearIdentity("Twitch");twitchStatus="Twitch: sign-in removed";}catch(Exception){MessageBox.Show(w,"Could not remove the sign-in.");}}));});

 page("YouTube","Import Google Desktop app credentials, then sign in. Shows chat, Super Chats, Super Stickers and membership events during a live broadcast. Alerts are checked about every 20 seconds; ordinary subscriber notifications are not included.",()=>youtubeStatus,row=>{row.Controls.Add(AccountConnectButton(()=>youtubeStop==null?"Connect YouTube":"Pause connection",ToggleYouTube));row.Controls.Add(Button("Import Google file",delegate{ImportGoogle();}));row.Controls.Add(Button("Sign out",async delegate{await Forget("youtube");}));});

 page("Streamlabs","Receive tips directly from Streamlabs. Set your Socket API token once, then connect. Twitch alerts continue to come from your direct Twitch connection.",()=>streamlabsStatus,row=>{row.Controls.Add(AccountConnectButton(()=>streamlabsStop==null?"Connect Streamlabs":"Pause connection",ToggleStreamlabs));row.Controls.Add(Button("Set token",delegate{SetStreamlabs();}));row.Controls.Add(Button("Sign out",async delegate{await Forget("streamlabs");}));});

 page("Kick","Kick delivers alerts through your Cloudflare receiver. Deploy the receiver and register the Kick app first, then enter the receiver settings here.",()=>kickStatus,row=>{row.Controls.Add(AccountConnectButton(()=>kickStop==null?"Connect Kick":"Pause connection",ToggleKick));row.Controls.Add(Button("Sign out on this PC",async delegate{await Forget("kick");}));row.Controls.Add(Button("Receiver settings",delegate{SetKick();}));});

 page("Bridge","Optional Streamer.bot connection for services you have not moved yet. Alerts from a service are ignored here while its direct connection is running.",()=>stop==null?"Bridge: disconnected":status.Text,row=>{row.Controls.Add(AccountConnectButton(()=>stop==null?"Connect bridge":"Disconnect",ToggleConnection));row.Controls.Add(Button("Bridge setup",delegate{ShowSetup();}));});if(selected!=null)foreach(TabPage tab in tabs.TabPages)if(tab.Text==selected)tabs.SelectedTab=tab;w.ShowDialog(this);}}

}

