using System;using System.Linq;using System.Net.Http;using System.Net.Http.Headers;using System.Text;using System.Threading;using System.Threading.Tasks;using System.Collections.Generic;
public static class ChatSend {
 static readonly SemaphoreSlim gate=new SemaphoreSlim(1);static DateTime last=DateTime.MinValue;
 static async Task<object> Request(HttpClient http,string url,string token,object body,string client=null){using(var r=new HttpRequestMessage(body==null?HttpMethod.Get:HttpMethod.Post,url)){r.Headers.Authorization=new AuthenticationHeaderValue("Bearer",token);if(client!=null)r.Headers.Add("Client-Id",client);if(body!=null)r.Content=new StringContent(Protocol.Json.Serialize(body),Encoding.UTF8,"application/json");using(var response=await http.SendAsync(r)){if(!response.IsSuccessStatusCode){if(url.EndsWith("/chat/send",StringComparison.Ordinal)){string reason="";try{reason=Protocol.Pick(Protocol.Json.DeserializeObject(await response.Content.ReadAsStringAsync()),"error");}catch{}if(reason=="Reconnect Kick to allow sending")throw new Exception("Sending permission is missing. In Notify, pause Kick, reconnect and approve chat sending.");if(reason=="Reconnect Kick")throw new Exception("Kick sign-in expired. Pause Kick and reconnect in Notify.");if(reason=="Kick rejected the message")throw new Exception("Kick rejected this message (HTTP "+(int)response.StatusCode+"). Reconnect Kick to renew sending permission.");if(response.StatusCode==System.Net.HttpStatusCode.NotFound)throw new Exception("Update the private Kick receiver in Cloudflare first.");}throw new Exception("Rejected (HTTP "+(int)response.StatusCode+"). Check permission or reconnect; not retried.");}return Protocol.Json.DeserializeObject(await response.Content.ReadAsStringAsync());}}}
 public static async Task<string> Send(string payload){
 if(!await gate.WaitAsync(0))return Protocol.Json.Serialize(new{error="A message is already sending."});
 try{if((DateTime.UtcNow-last).TotalSeconds<2)return Protocol.Json.Serialize(new{error="Wait two seconds before sending again."});
 var input=Protocol.Json.DeserializeObject(payload);var text=Protocol.Pick(input,"text").Trim();var target=Protocol.Pick(input,"target");if(text.Length<1||text.Length>200||!new[]{"all","Twitch","YouTube","Kick"}.Contains(target))return Protocol.Json.Serialize(new{error="Choose a destination and enter 1–200 characters."});last=DateTime.UtcNow;
 var results=new List<object>();using(var http=new HttpClient(new HttpClientHandler{AllowAutoRedirect=false,UseCookies=false}){Timeout=TimeSpan.FromSeconds(12),MaxResponseContentBufferSize=1048576}){
 foreach(var platform in target=="all"?new[]{"Twitch","YouTube","Kick"}:new[]{target}){try{
 if(platform=="Twitch"){var tokens=await TokenRenewal.Twitch();var user=await Request(http,"https://api.twitch.tv/helix/users",tokens.Access,null,DirectTwitch.ClientId);var id=Protocol.Pick((Protocol.Items(Protocol.Get(user,"data"))??new object[0]).FirstOrDefault(),"id");if(id=="")throw new Exception("Account unavailable.");var sent=await Request(http,"https://api.twitch.tv/helix/chat/messages",tokens.Access,new{broadcaster_id=id,sender_id=id,message=text},DirectTwitch.ClientId);if(!Protocol.Pick((Protocol.Items(Protocol.Get(sent,"data"))??new object[0]).FirstOrDefault(),"is_sent").Equals("true",StringComparison.OrdinalIgnoreCase))throw new Exception("Twitch did not accept the message.");}
 else if(platform=="YouTube"){var tokens=await TokenRenewal.YouTube();var live=await Request(http,"https://www.googleapis.com/youtube/v3/liveBroadcasts?part=snippet&broadcastStatus=active&maxResults=50",tokens.Access,null);var chats=(Protocol.Items(Protocol.Get(live,"items"))??new object[0]).Select(x=>Protocol.Pick(x,"snippet.liveChatId")).Where(x=>x!="").Distinct().ToArray();if(chats.Length!=1)throw new Exception(chats.Length==0?"No active live chat.":"Multiple active broadcasts. Send from YouTube to choose the correct chat.");await Request(http,"https://www.googleapis.com/youtube/v3/liveChat/messages?part=snippet",tokens.Access,new{snippet=new{liveChatId=chats[0],type="textMessageEvent",textMessageDetails=new{messageText=text}}});}
 else {var kick=AccountStore.Read<KickSettings>("kick");if(kick==null)throw new Exception("Not configured.");Uri origin;if(!Uri.TryCreate(kick.Url,UriKind.Absolute,out origin)||origin.Scheme!="https"||origin.UserInfo!=""||origin.AbsolutePath!="/"||origin.Query!=""||origin.Fragment!="")throw new Exception("Invalid receiver address.");await Request(http,kick.Url.TrimEnd('/')+"/chat/send",kick.Key,new{text=text});}
 results.Add(new{platform=platform,sent=true,message="Sent"});
 }catch(Exception e){var safe=e is TaskCanceledException||e is HttpRequestException?"Delivery unknown. Check chat before trying again.":e.Message;results.Add(new{platform=platform,sent=false,message=safe});}}
 }return Protocol.Json.Serialize(new{results=results});
 }catch{return Protocol.Json.Serialize(new{error="Could not send. Check your connection."});}finally{gate.Release();}}
}
