using System;using System.Collections.Generic;using System.Linq;using System.Drawing;using System.Windows.Forms;using System.Net.Http;using System.Threading;using System.Threading.Tasks;
public sealed class CollabSettings {public string Origin="",Credential="",Reminder="";public DateTime Due=DateTime.MinValue;public bool Notified;}
public static class CollabView {
 public static string Origin(string text){Uri u;if(!Uri.TryCreate(text,UriKind.Absolute,out u)||u.UserInfo!=""||u.Query!=""||u.Fragment!=""||u.AbsolutePath!="/"||(u.Scheme!="https"&&u.Scheme!="http"))throw new ArgumentException("Use an HTTP or HTTPS server address without a path.");return u.GetLeftPart(UriPartial.Authority);}
 public static Dictionary<string,string> Entries(object data){var result=new Dictionary<string,string>();string me=Protocol.Pick(data,"me.id");foreach(var p in (Protocol.Items(Protocol.Get(data,"peers"))??new object[0]).Take(500))result["peer:"+Protocol.Pick(p,"id")]=Protocol.Pick(p,"displayName","id")+": "+Protocol.Pick(p,"state");foreach(var type in new[]{"collaborations","requests"})foreach(var p in (Protocol.Items(Protocol.Get(data,type))??new object[0]).Take(500)){if(Protocol.Pick(p,"peer")!=me&&Protocol.Pick(p,"owner")!=me)continue;result[type+":"+Protocol.Pick(p,"id")]=(Protocol.Pick(p,"peer")==me?"Incoming from ":"Request to ")+(Protocol.Pick(p,"peer")==me?Protocol.Pick(p,"owner"):Protocol.Pick(p,"peer"))+" · "+Protocol.Pick(p,"status");}return result;}
}
public partial class MainWindow {
 CollabSettings collab=new CollabSettings();CancellationTokenSource collabStop;Dictionary<string,string> collabEntries=new Dictionary<string,string>();string collabStatus="Disconnected";
 void InitCollab(){try{collab=AccountStore.Read<CollabSettings>("collab")??new CollabSettings();}catch{collabStatus="Saved login could not be unlocked.";}FormClosed+=delegate{if(collabStop!=null)collabStop.Cancel();PublishCollab(false);};}
 async void ConnectCollab(){if(collabStop!=null)collabStop.Cancel();var source=new CancellationTokenSource();collabStop=source;bool first=true;collabSession=Guid.NewGuid().ToString("N");collabEntries.Clear();using(var http=new HttpClient(new HttpClientHandler{AllowAutoRedirect=false,UseCookies=false}){Timeout=TimeSpan.FromSeconds(8),MaxResponseContentBufferSize=1048576}){http.DefaultRequestHeaders.Authorization=new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer",collab.Credential);while(!source.IsCancellationRequested){try{using(var response=await http.GetAsync(collab.Origin+"/api/v3/view",source.Token)){if(response.StatusCode==System.Net.HttpStatusCode.Unauthorized||response.StatusCode==System.Net.HttpStatusCode.Forbidden){collabStatus="Login rejected. Check your personal username:token.";PublishCollab(false);break;}response.EnsureSuccessStatusCode();var entries=CollabView.Entries(Protocol.Json.DeserializeObject(await response.Content.ReadAsStringAsync()));if(source.IsCancellationRequested)break;if(!first)foreach(var item in entries){string old;if(!collabEntries.TryGetValue(item.Key,out old)||old!=item.Value)Add(new Alert{Time=DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss"),Platform="UniversalCollab",Kind="Collaboration",Name="Collaboration update",Detail=item.Value});}first=false;collabEntries=entries;collabStatus="Connected · Updates every 10 seconds";PublishCollab(true);}}catch{if(source.IsCancellationRequested)break;collabStatus="Unavailable · Retrying";PublishCollab(false);}try{await Task.Delay(10000,source.Token);}catch{break;}}}source.Dispose();if(collabStop==source)collabStop=null;}
 void PublishCollab(bool online){try{var folder=System.IO.Path.Combine(IntegratedHost.DataRoot);System.IO.Directory.CreateDirectory(folder);var file=System.IO.Path.Combine(folder,"collab-presence.json");var value=new{origin=collab.Origin,user=collab.Credential.Split(':')[0],connected=online,session=collabSession,reminder=collab.Reminder,due=collab.Due==DateTime.MinValue?0:(long)(collab.Due-new DateTime(1970,1,1)).TotalMilliseconds,notified=collab.Notified,updated=(long)(DateTime.UtcNow-new DateTime(1970,1,1)).TotalMilliseconds};System.IO.File.WriteAllText(file+".tmp",Protocol.Json.Serialize(value));if(System.IO.File.Exists(file))System.IO.File.Replace(file+".tmp",file,null);else System.IO.File.Move(file+".tmp",file);}catch{}}
 string collabSession=Guid.NewGuid().ToString("N");
 void ShowCollab(){using(var w=new Form{Text="UniversalCollab integration",Size=new Size(760,820),MinimumSize=new Size(700,640),StartPosition=FormStartPosition.CenterParent,BackColor=Theme.Canvas,ForeColor=Theme.Text,Font=new Font("Segoe UI",10)}){
 var p=new FlowLayoutPanel{Dock=DockStyle.Fill,FlowDirection=FlowDirection.TopDown,WrapContents=false,AutoScroll=true,Padding=new Padding(24)};w.Controls.Add(p);
 Func<string,int,Label> label=(text,height)=>new Label{Text=text,Width=650,Height=height,ForeColor=Theme.Muted,Margin=new Padding(0,0,0,8)};
 var heading=label("UniversalCollab",36);heading.Font=new Font("Segoe UI",20,FontStyle.Bold);heading.ForeColor=Theme.Text;p.Controls.Add(heading);
 p.Controls.Add(label("Connect your relay to receive collaboration requests and teammate updates.",40));
 var badge=label("Disconnected",30);badge.Font=new Font("Segoe UI",11,FontStyle.Bold);p.Controls.Add(badge);
 Func<string,TextBox> field=text=>new TextBox{Text=text,Width=630,BackColor=Theme.Surface,ForeColor=Theme.Text,BorderStyle=BorderStyle.FixedSingle,Font=new Font("Segoe UI",12),Margin=new Padding(0,0,0,16)};
 p.Controls.Add(label("Relay server address",22));var url=field(collab.Origin);p.Controls.Add(url);
 var transport=label("",36);Action showTransport=delegate{transport.Text=url.Text.Trim().StartsWith("http://",StringComparison.OrdinalIgnoreCase)?"HTTP: your personal token travels without encryption.":"Enter the control address saved in UniversalCollab.";};url.TextChanged+=delegate{showTransport();};showTransport();p.Controls.Add(transport);
 p.Controls.Add(label("Personal relay login",22));var credential=field(collab.Credential);credential.UseSystemPasswordChar=true;p.Controls.Add(credential);p.Controls.Add(label("Format: username:token. Use your personal token, not the shared join password.",36));
 var actions=new FlowLayoutPanel{Width=650,Height=52,Margin=new Padding(0,0,0,16)};
 actions.Controls.Add(Button("Save & connect",delegate{try{var origin=CollabView.Origin(url.Text.Trim());var login=credential.Text.Trim();if(!System.Text.RegularExpressions.Regex.IsMatch(login,@"^[A-Za-z0-9_-]{1,32}:[A-Za-z0-9_-]{16,256}$"))throw new ArgumentException("Enter your relay username followed by a colon and your personal token.");collab.Origin=origin;collab.Credential=login;AccountStore.Save("collab",collab);collabStatus="Connecting...";ConnectCollab();}catch(Exception e){MessageBox.Show(w,e.Message,"Connection details");}}));
 actions.Controls.Add(Button("Disconnect",delegate{if(collabStop!=null){collabStop.Cancel();collabStop=null;}collabStatus="Disconnected";collabEntries.Clear();PublishCollab(false);}));p.Controls.Add(actions);
 p.Controls.Add(label("Teammate status, requests and reminders now appear in UniversalCollab. Keep both apps open on this computer.",60));
 using(var timer=new System.Windows.Forms.Timer{Interval=500}){timer.Tick+=delegate{badge.Text=collabStatus;badge.ForeColor=collabStatus.StartsWith("Connected")?Color.LightGreen:Theme.Accent;};timer.Start();w.ShowDialog(this);}
 }}
}
