using System;using System.Collections.Generic;using System.Drawing;using System.Linq;using System.Windows.Forms;using System.Text.RegularExpressions;
public static class CombinedChat {
 public static Rectangle AnimationBounds(Rectangle row){return new Rectangle(row.X,row.Y+32,row.Width,Math.Max(0,row.Height-32));}
 public static Alert Kick(object envelope){var e=Protocol.Get(envelope,"data");var a=new Alert{Kind="Chat",Platform="Kick",Name=Protocol.Pick(e,"sender.username"),Time=Protocol.Pick(e,"created_at"),Detail=Protocol.Pick(e,"content")};
  a.Detail=Regex.Replace(a.Detail,@"\[emote:([0-9]+):([^\]\r\n]+)\]",m=>{string name=m.Groups[2].Value;a.Emotes.Add(new Emote{Name=name,Url="https://files.kick.com/emotes/"+m.Groups[1].Value+"/fullsize"});return " "+name+" ";});return a;
 }
}
// A managed, buffered paint surface: native ListBox erases between animation frames.
public sealed class BufferedChatList : Control {
 public readonly List<Alert> Items=new List<Alert>();
 readonly VScrollBar scroll=new VScrollBar();readonly List<int> tops=new List<int>();readonly List<int> heights=new List<int>();
 public event MeasureItemEventHandler MeasureItem;public event DrawItemEventHandler DrawItem;
 int selected=-1;bool measuring;
 public BufferedChatList(){SetStyle(ControlStyles.UserPaint|ControlStyles.AllPaintingInWmPaint|ControlStyles.OptimizedDoubleBuffer|ControlStyles.ResizeRedraw|ControlStyles.Opaque,true);TabStop=true;scroll.Dock=DockStyle.Right;scroll.SmallChange=32;scroll.ValueChanged+=delegate{Invalidate();};Controls.Add(scroll);}
 public object SelectedItem{get{return selected>=0&&selected<Items.Count?Items[selected]:null;}}
 public int TopIndex{get{for(int i=0;i<tops.Count;i++)if(tops[i]+heights[i]>scroll.Value)return i;return 0;}set{MeasureRows();if(value>=0&&value<tops.Count)scroll.Value=Math.Min(tops[value],Math.Max(0,scroll.Maximum-scroll.LargeChange+1));Invalidate();}}
 public void BeginUpdate(){}
 public void EndUpdate(){selected=-1;MeasureRows();Invalidate();}
 void MeasureRows(){if(measuring||IsDisposed)return;measuring=true;try{tops.Clear();heights.Clear();int top=0;using(var g=CreateGraphics()){for(int i=0;i<Items.Count;i++){var args=new MeasureItemEventArgs(g,i,76);if(MeasureItem!=null)MeasureItem(this,args);tops.Add(top);int height=Math.Max(40,args.ItemHeight);heights.Add(height);top+=height;}}scroll.LargeChange=Math.Max(1,ClientSize.Height);scroll.Maximum=Math.Max(0,top-1);int limit=Math.Max(0,scroll.Maximum-scroll.LargeChange+1);if(scroll.Value>limit)scroll.Value=limit;scroll.Enabled=limit>0;}finally{measuring=false;}}
 public Rectangle GetItemRectangle(int index){if(tops.Count!=Items.Count)MeasureRows();return index>=0&&index<tops.Count?new Rectangle(0,tops[index]-scroll.Value,Math.Max(1,ClientSize.Width-scroll.Width),heights[index]):Rectangle.Empty;}
 protected override void OnResize(EventArgs e){base.OnResize(e);MeasureRows();Invalidate();}
 protected override void OnPaintBackground(PaintEventArgs e){}
 protected override void OnPaint(PaintEventArgs e){using(var brush=new SolidBrush(BackColor))e.Graphics.FillRectangle(brush,e.ClipRectangle);if(tops.Count!=Items.Count)MeasureRows();for(int i=TopIndex;i<Items.Count;i++){var row=GetItemRectangle(i);if(row.Top>=ClientSize.Height)break;if(!row.IntersectsWith(e.ClipRectangle))continue;var saved=e.Graphics.Save();e.Graphics.SetClip(Rectangle.Intersect(row,e.ClipRectangle));if(DrawItem!=null)DrawItem(this,new DrawItemEventArgs(e.Graphics,Font,row,i,DrawItemState.None,ForeColor,BackColor));e.Graphics.Restore(saved);}base.OnPaint(e);}
 protected override void OnMouseDown(MouseEventArgs e){Focus();for(int i=TopIndex;i<Items.Count;i++){var r=GetItemRectangle(i);if(r.Top>Height)break;if(r.Contains(e.Location)){selected=i;break;}}base.OnMouseDown(e);}
 protected override void OnMouseWheel(MouseEventArgs e){int limit=Math.Max(0,scroll.Maximum-scroll.LargeChange+1);scroll.Value=Math.Max(0,Math.Min(limit,scroll.Value-e.Delta/120*96));base.OnMouseWheel(e);}
 protected override void OnKeyDown(KeyEventArgs e){int delta=e.KeyCode==Keys.PageDown?Height:e.KeyCode==Keys.PageUp?-Height:e.KeyCode==Keys.Down?32:e.KeyCode==Keys.Up?-32:0;if(delta!=0){scroll.Value=Math.Max(0,Math.Min(Math.Max(0,scroll.Maximum-scroll.LargeChange+1),scroll.Value+delta));e.Handled=true;}base.OnKeyDown(e);}
}

public partial class MainWindow {
 readonly List<Alert> chatMessages=new List<Alert>();Form chatWindow;BufferedChatList chatList;TextBox chatSearch;CheckBox chatPause;Label chatState;
 void AddChat(Alert a){a.Detail=(a.Detail??"");if(a.Detail.Length>4000)a.Detail=a.Detail.Substring(0,4000);if(string.IsNullOrWhiteSpace(a.Detail))return;chatMessages.Add(a);if(chatMessages.Count>500)chatMessages.RemoveAt(0);PrepareMessage(a);if(chatList!=null&&!chatList.IsDisposed&&!chatPause.Checked){if((a.Name+" "+a.Detail).IndexOf(chatSearch.Text,StringComparison.OrdinalIgnoreCase)>=0){chatList.Items.Add(a);while(chatList.Items.Count>500)chatList.Items.RemoveAt(0);chatList.TopIndex=chatList.Items.Count-1;}}}
 void RefreshChat(){if(chatList==null||chatList.IsDisposed)return;string q=chatSearch.Text;chatList.BeginUpdate();chatList.Items.Clear();foreach(var a in chatMessages)if((a.Name+" "+a.Detail).IndexOf(q,StringComparison.OrdinalIgnoreCase)>=0)chatList.Items.Add(a);chatList.EndUpdate();if(chatList.Items.Count>0)chatList.TopIndex=chatList.Items.Count-1;}
 void ShowCombinedChat(){if(chatWindow!=null&&!chatWindow.IsDisposed){chatWindow.Show();chatWindow.Activate();return;}
  var w=new Form{Text="Combined chat · UniversalStream Assist",Size=new Size(820,650),MinimumSize=new Size(520,380),BackColor=Theme.Canvas,ForeColor=Theme.Text,Font=Font,Icon=Icon};chatWindow=w;
  var layout=new TableLayoutPanel{Dock=DockStyle.Fill,Padding=new Padding(18),ColumnCount=1,RowCount=5};foreach(int h in new[]{42,90,48})layout.RowStyles.Add(new RowStyle(SizeType.Absolute,h));layout.RowStyles.Add(new RowStyle(SizeType.Percent,100));layout.RowStyles.Add(new RowStyle(SizeType.Absolute,68));w.Controls.Add(layout);
  layout.Controls.Add(Label("All your conversations, together",20,Theme.Text,true),0,0);
  var bar=new FlowLayoutPanel{Dock=DockStyle.Fill};chatPause=new CheckBox{Text="Pause feed",AutoSize=true,Margin=new Padding(4,12,8,0)};chatPause.CheckedChanged+=delegate{if(!chatPause.Checked)RefreshChat();};bar.Controls.Add(chatPause);bar.Controls.Add(Button("Clear",delegate{chatMessages.Clear();RefreshChat();}));bar.Controls.Add(Button("Sample chat",delegate{foreach(var p in new[]{"Twitch","YouTube","Kick"})AddChat(new Alert{Platform=p,Kind="Chat",Name="Sample viewer",Detail="Hello from "+p+"!",Time=DateTime.Now.ToString("HH:mm:ss")});}));bar.Controls.Add(Button("Appearance",delegate{ShowChatAppearance();}));bar.Controls.Add(Button("OBS setup",delegate{ShowObs();}));layout.Controls.Add(bar,0,1);
  chatSearch=new TextBox{Dock=DockStyle.Fill,BackColor=Theme.Raised,ForeColor=Theme.Text,BorderStyle=BorderStyle.FixedSingle,AccessibleName="Search combined chat"};chatSearch.TextChanged+=delegate{RefreshChat();};layout.Controls.Add(chatSearch,0,2);
  chatList=new BufferedChatList{Dock=DockStyle.Fill,BackColor=ColorTranslator.FromHtml(obs.style.background),ForeColor=ColorTranslator.FromHtml(obs.style.text),Font=chatFont??Font};
  chatList.MeasureItem+=delegate(object sender,MeasureItemEventArgs e){if(e.Index<0)return;var a=(Alert)chatList.Items[e.Index];int width=Math.Max(100,chatList.ClientSize.Width-32);e.ItemHeight=Math.Min(2000,ChatHeaderHeight+12+Math.Max(obs.style.emote+4,TextRenderer.MeasureText(a.Detail,chatFont??Font,new Size(width,int.MaxValue),TextFormatFlags.WordBreak).Height*2));};
  chatList.DrawItem+=delegate(object sender,DrawItemEventArgs e){if(e.Index<0)return;var a=(Alert)chatList.Items[e.Index];e.DrawBackground();DateTimeOffset stamp;string time=DateTimeOffset.TryParse(a.Time,out stamp)?stamp.ToLocalTime().ToString("HH:mm:ss"):a.Time;var header=new Rectangle(e.Bounds.X+10,e.Bounds.Y+5,e.Bounds.Width-20,ChatHeaderHeight-7);if(e.Graphics.IsVisible(header))TextRenderer.DrawText(e.Graphics,(obs.style.platforms?a.Platform+"  ·  ":"")+a.Name+(obs.style.timestamps?"  ·  "+time:""),chatFont??Font,header,ColorTranslator.FromHtml(obs.style.name),TextFormatFlags.EndEllipsis|TextFormatFlags.PreserveGraphicsClipping);InlineMessage.Draw(e.Graphics,chatFont??Font,chatList.ForeColor,new Rectangle(e.Bounds.X+10,e.Bounds.Y+ChatHeaderHeight,e.Bounds.Width-24,e.Bounds.Height-ChatHeaderHeight-2),a.Runs,emoteCache,true,obs.style.emote);};
  chatList.DoubleClick+=delegate{var a=chatList.SelectedItem as Alert;if(a!=null)MessageBox.Show(w,a.Detail,a.Platform+" · "+a.Name);};chatList.Resize+=delegate{RefreshChat();};layout.Controls.Add(chatList,0,3);chatState=Label(twitchStatus+"\n"+youtubeStatus+"\n"+kickStatus,9,Theme.Muted,false);layout.Controls.Add(chatState,0,4);
  var timer=new System.Windows.Forms.Timer{Interval=33};timer.Tick+=delegate{string state=twitchStatus+"\n"+youtubeStatus+"\n"+kickStatus;if(chatState.Text!=state)chatState.Text=state; if(w.WindowState!=FormWindowState.Minimized&&chatList.Visible&&chatList.Items.Count>0){int first=chatList.TopIndex;for(int i=first;i<chatList.Items.Count;i++){var bounds=chatList.GetItemRectangle(i);if(bounds.Top>chatList.Height)break;var a=(Alert)chatList.Items[i];if(a.Runs.Any(r=>emoteCache.IsAnimated(r.Url)))chatList.Invalidate(new Rectangle(bounds.X,bounds.Y+ChatHeaderHeight,bounds.Width,Math.Max(0,bounds.Height-ChatHeaderHeight)));}}};timer.Start();w.FormClosed+=delegate{timer.Dispose();chatWindow=null;chatList=null;};w.Show(this);RefreshChat();
 }
}
