using System;using System.Collections.Generic;using System.Diagnostics;using System.Net.Http;using System.Net.Http.Headers;using System.Threading;using System.Threading.Tasks;
public sealed class KickSettings {public string Url,Key;}
public static class KickEvents {
 public static Alert Parse(object envelope){string type=Protocol.Pick(envelope,"type");if(type=="chat.message.sent")return CombinedChat.Kick(envelope);var e=Protocol.Get(envelope,"data");string kind,detail="",name=Protocol.Pick(e,"follower.username","subscriber.username","gifter.username","sender.username");switch(type){case "channel.followed":kind="Follow";detail="Welcome to the community!";break;case "channel.subscription.new":kind="Subscription";detail="New subscriber";break;case "channel.subscription.renewal":kind="Resubscription";detail=Protocol.Pick(e,"duration")+" months";break;case "channel.subscription.gifts":kind="MassGiftSubscription";var gifts=Protocol.Items(Protocol.Get(e,"giftees"));detail=(gifts==null?Protocol.Pick(e,"total"):gifts.Length.ToString())+" gifted subscriptions";break;case "kicks.gifted":kind="KicksGifted";detail=Protocol.Pick(e,"gift.amount","amount")+" Kicks  "+Protocol.Pick(e,"gift.message","message");break;default:return null;}DateTimeOffset time;if(!DateTimeOffset.TryParse(Protocol.Pick(envelope,"time"),out time))time=DateTimeOffset.Now;return new Alert{Time=time.ToLocalTime().ToString("yyyy-MM-dd HH:mm:ss"),Platform="Kick",Kind=kind,Name=name==""?"Anonymous":name,Detail=detail.Trim()};}
}
public sealed class DirectKick:IDisposable {
 readonly KickSettings config;readonly Action<string> status;readonly Action<string> identity;readonly Action<Alert> alert;readonly HttpClient http=new HttpClient(new HttpClientHandler{AllowAutoRedirect=false,UseCookies=false}){Timeout=TimeSpan.FromSeconds(20),MaxResponseContentBufferSize=2097152};
 public DirectKick(KickSettings config,Action<string> status,Action<Alert> alert,Action<string> identity=null){this.identity=identity;this.config=config;this.status=status;this.alert=alert;}
 async Task<object> Request(string path,bool post,CancellationToken ct){using(var request=new HttpRequestMessage(post?HttpMethod.Post:HttpMethod.Get,config.Url.TrimEnd('/')+path)){request.Headers.Authorization=new AuthenticationHeaderValue("Bearer",config.Key);using(var response=await http.SendAsync(request,ct)){if((int)response.StatusCode==401)throw new TwitchSignInRequired("Kick: receiver key rejected. Check Kick settings.");if(!response.IsSuccessStatusCode)throw new Exception("Receiver unavailable");return Protocol.Json.DeserializeObject(await response.Content.ReadAsStringAsync());}}}
 public async Task Run(CancellationToken ct){try{var initial=await Request("/events?after=latest",false,ct);string cursor=Protocol.Pick(initial,"cursor");bool connected=Protocol.Pick(initial,"connected").Equals("true",StringComparison.OrdinalIgnoreCase);if(!Protocol.Pick(initial,"send_ready").Equals("true",StringComparison.OrdinalIgnoreCase)||!connected||!Protocol.Pick(initial,"chat_ready").Equals("true",StringComparison.OrdinalIgnoreCase)){var login=await Request("/connect",true,ct);string url=Protocol.Pick(login,"url");Uri uri;if(!Uri.TryCreate(url,UriKind.Absolute,out uri)||uri.Scheme!="https"||uri.Host!="id.kick.com")throw new TwitchSignInRequired("Kick: the receiver returned an invalid sign-in page.");Process.Start(new ProcessStartInfo(url){UseShellExecute=true});status("Kick: approve sign-in in your browser");}int failures=0;while(!ct.IsCancellationRequested){try{var response=await Request("/events?after="+Uri.EscapeDataString(cursor),false,ct);connected=Protocol.Pick(response,"connected").Equals("true",StringComparison.OrdinalIgnoreCase);foreach(var item in Protocol.Items(Protocol.Get(response,"events"))??new object[0]){string broadcaster=Protocol.Pick(item,"data.broadcaster.username","data.broadcaster.name");if(identity!=null&&broadcaster!="")identity(broadcaster);var parsed=KickEvents.Parse(item);if(parsed!=null)alert(parsed);}cursor=Protocol.Pick(response,"cursor");status(connected?"Kick connected · Listening for alerts.":"Kick: waiting for sign-in or receiver setup");failures=0;}catch(TwitchSignInRequired){throw;}catch(OperationCanceledException){if(ct.IsCancellationRequested)throw;failures++;status("Kick: receiver timed out. Retrying…");}catch(Exception){failures++;status("Kick: receiver unavailable. Retrying…");}await Task.Delay(Math.Min(60000,5000*(1+failures)),ct);}}catch(TwitchSignInRequired e){status(e.Message);}catch(OperationCanceledException){status("Kick: disconnected");}catch(Exception){status("Kick: receiver is not ready. Check the Cloudflare setup.");}}
 public void Dispose(){http.Dispose();}
}
