using System;
using System.Collections.Generic;
using System.IO;
using System.Net.WebSockets;
using System.Security.Cryptography;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

public static class AccountStore {
 static string FileName(string name){if(name!="collab"&&name!="integrations"&&name!="pulsoid"&&name!="obs-view"&&name!="streamlabs"&&name!="google-client"&&name!="youtube"&&name!="kick")throw new ArgumentException("Unknown account");return Path.Combine(IntegratedHost.DataRoot,name+".dat");}
 public static T Read<T>(string name) where T:class{try{return Protocol.Json.Deserialize<T>(Encoding.UTF8.GetString(ProtectedData.Unprotect(File.ReadAllBytes(FileName(name)),null,DataProtectionScope.CurrentUser)));}catch(IOException){return null;}catch(CryptographicException){return null;}catch(ArgumentException){return null;}}
 public static void Save(string name,object value){string path=FileName(name);byte[] bytes=ProtectedData.Protect(Encoding.UTF8.GetBytes(Protocol.Json.Serialize(value)),null,DataProtectionScope.CurrentUser);Directory.CreateDirectory(Path.GetDirectoryName(path));File.WriteAllBytes(path+".tmp",bytes);if(File.Exists(path))File.Replace(path+".tmp",path,null);else File.Move(path+".tmp",path);}
 public static void Forget(string name){string path=FileName(name);if(File.Exists(path))File.Delete(path);}
}
public sealed class StreamlabsEvents {
 readonly HashSet<string> seen=new HashSet<string>();readonly Queue<string> order=new Queue<string>();
 public List<Alert> Parse(string packet){var output=new List<Alert>();if(!packet.StartsWith("42["))return output;var parts=Protocol.Items(Protocol.Json.DeserializeObject(packet.Substring(2)));if(parts==null||parts.Length<2||parts[0].ToString()!="event")return output;var data=parts[1];string provider=Protocol.Pick(data,"for");if(Protocol.Pick(data,"type")!="donation"||(provider!=""&&provider!="streamlabs"))return output;var items=Protocol.Items(Protocol.Get(data,"message"));if(items==null)return output;int index=0;foreach(var item in items){string id=Protocol.Pick(item,"_id","id");if(id==""){string envelope=Protocol.Pick(data,"event_id");if(envelope!="")id=envelope+":"+index;}index++;if(id!=""){if(!seen.Add(id))continue;order.Enqueue(id);while(order.Count>4000)seen.Remove(order.Dequeue());}string name=Protocol.Pick(item,"name","from"),money=Protocol.Pick(item,"formattedAmount","formatted_amount");if(money=="")money=Protocol.Pick(item,"amount")+" "+Protocol.Pick(item,"currency");output.Add(new Alert{Time=DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss"),Platform="Streamlabs",Kind="Donation",Name=name==""?"Viewer":name,Detail=(money+"  "+Protocol.Pick(item,"message")).Trim(),Demo=Protocol.Pick(data,"isTest","is_test").Equals("true",StringComparison.OrdinalIgnoreCase),Emotes=Protocol.ReadEmotes(item)});}return output;}
}
public sealed class DirectStreamlabs {
 readonly Action<string> status;readonly Action<Alert> alert;readonly StreamlabsEvents events=new StreamlabsEvents();
 string endpoint="wss://sockets.streamlabs.com/socket.io/?EIO=3&transport=websocket&token=";
 public DirectStreamlabs(Action<string> status,Action<Alert> alert){this.status=status;this.alert=alert;}
 static async Task<string> Read(ClientWebSocket ws,CancellationToken ct){using(var stream=new MemoryStream()){byte[] b=new byte[8192];WebSocketReceiveResult frame;do{frame=await ws.ReceiveAsync(new ArraySegment<byte>(b),ct);if(frame.MessageType==WebSocketMessageType.Close)throw new IOException("Connection closed");if(frame.MessageType!=WebSocketMessageType.Text)throw new IOException("Invalid event format");stream.Write(b,0,frame.Count);if(stream.Length>1048576)throw new IOException("Event too large");}while(!frame.EndOfMessage);return Encoding.UTF8.GetString(stream.ToArray());}}
 static Task Send(ClientWebSocket ws,string text,CancellationToken ct){return ws.SendAsync(new ArraySegment<byte>(Encoding.UTF8.GetBytes(text)),WebSocketMessageType.Text,true,ct);}
 static int Number(object o,string path,int fallback){int value;return int.TryParse(Protocol.Pick(o,path),out value)?Math.Max(100,Math.Min(value,120000)):fallback;}
 async Task Session(string token,CancellationToken ct){using(var ws=new ClientWebSocket())using(var session=CancellationTokenSource.CreateLinkedTokenSource(ct)){ws.Options.KeepAliveInterval=TimeSpan.Zero;try{using(var deadline=CancellationTokenSource.CreateLinkedTokenSource(ct)){deadline.CancelAfter(20000);await ws.ConnectAsync(new Uri(endpoint+Uri.EscapeDataString(token)),deadline.Token);string welcome=await Read(ws,deadline.Token);if(!welcome.StartsWith("0"))throw new IOException("Missing Streamlabs welcome");var data=Protocol.Json.DeserializeObject(welcome.Substring(1));int interval=Number(data,"pingInterval",25000),timeout=Number(data,"pingTimeout",20000);Task<string> read=Read(ws,session.Token);DateTime nextPing=DateTime.UtcNow.AddMilliseconds(interval),pongDeadline=DateTime.MaxValue,namespaceDeadline=DateTime.UtcNow.AddSeconds(20);bool joined=false;
 while(!ct.IsCancellationRequested){DateTime due=nextPing<pongDeadline?nextPing:pongDeadline;if(!joined&&namespaceDeadline<due)due=namespaceDeadline;int wait=(int)Math.Max(1,(due-DateTime.UtcNow).TotalMilliseconds);using(var tick=CancellationTokenSource.CreateLinkedTokenSource(ct)){var delay=Task.Delay(wait,tick.Token);var completed=await Task.WhenAny(read,delay);if(completed==read){tick.Cancel();string packet=await read;if(packet.StartsWith("40")){joined=true;status("Streamlabs connected · Listening for tips.");}else if(packet.StartsWith("44"))throw new UnauthorizedAccessException();else if(packet=="3"){pongDeadline=DateTime.MaxValue;nextPing=DateTime.UtcNow.AddMilliseconds(interval);}else if(packet=="1"||packet=="41")throw new IOException("Streamlabs disconnected");else if(packet.StartsWith("42"))foreach(var a in events.Parse(packet))alert(a);read=Read(ws,session.Token);}else{ct.ThrowIfCancellationRequested();if(DateTime.UtcNow>=pongDeadline)throw new IOException("Heartbeat timed out");if(!joined&&DateTime.UtcNow>=namespaceDeadline)throw new UnauthorizedAccessException();if(DateTime.UtcNow>=nextPing){await Send(ws,"2",ct);nextPing=DateTime.MaxValue;pongDeadline=DateTime.UtcNow.AddMilliseconds(timeout);}}}}
 }}finally{session.Cancel();ws.Abort();}}}
 public async Task Run(string token,CancellationToken ct){int failures=0;while(!ct.IsCancellationRequested){try{status("Streamlabs: connecting…");await Session(token,ct);}catch(UnauthorizedAccessException){status("Streamlabs: token rejected. Open Accounts and replace the Socket API token.");return;}catch(OperationCanceledException){if(ct.IsCancellationRequested)return;status("Streamlabs: connection timed out. Retrying…");}catch(Exception){if(ct.IsCancellationRequested)return;status("Streamlabs: connection interrupted. Check the token and internet connection.");}try{await Task.Delay(TimeSpan.FromSeconds(Math.Min(60,5*Math.Pow(2,Math.Min(failures++,4)))),ct);}catch(OperationCanceledException){return;}}}
}
