using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Net.WebSockets;
using System.Security.Cryptography;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

public sealed class TwitchTokens {public string Access,Refresh;public DateTime Expires;}
public static class TwitchVault {
 static string PathName{get{return Path.Combine(IntegratedHost.DataRoot,"twitch.dat");}}
 public static byte[] Protect(TwitchTokens value){return ProtectedData.Protect(Encoding.UTF8.GetBytes(Protocol.Json.Serialize(value)),null,DataProtectionScope.CurrentUser);}
 public static TwitchTokens Unprotect(byte[] bytes){return Protocol.Json.Deserialize<TwitchTokens>(Encoding.UTF8.GetString(ProtectedData.Unprotect(bytes,null,DataProtectionScope.CurrentUser)));}
 public static TwitchTokens Read(){try{return Unprotect(File.ReadAllBytes(PathName));}catch(IOException){return null;}catch(CryptographicException){return null;}catch(ArgumentException){return null;}}
 public static void Save(TwitchTokens value){Directory.CreateDirectory(Path.GetDirectoryName(PathName));string temp=PathName+".tmp";File.WriteAllBytes(temp,Protect(value));if(File.Exists(PathName))File.Replace(temp,PathName,null);else File.Move(temp,PathName);}
 public static void Forget(){if(File.Exists(PathName))File.Delete(PathName);}
}
public sealed class TwitchApiError : Exception {public readonly int Code;public TwitchApiError(int code):base("Twitch returned HTTP "+code+"."){Code=code;}}
public sealed class TwitchSignInRequired : Exception {public TwitchSignInRequired(string text):base(text){}}
public static class TwitchEvents {
 public static readonly string[] Types={"channel.follow","channel.subscribe","channel.subscription.message","channel.subscription.gift","channel.cheer","channel.raid","channel.chat.message"};
 public static object Subscription(string type,string user,string session){var condition=new Dictionary<string,string>();condition[type=="channel.raid"?"to_broadcaster_user_id":"broadcaster_user_id"]=user;if(type=="channel.follow")condition["moderator_user_id"]=user;if(type=="channel.chat.message")condition["user_id"]=user;return new{type=type,version=type=="channel.follow"?"2":"1",condition=condition,transport=new{method="websocket",session_id=session}};}
 public static List<Emote> Emotes(object e){var result=new List<Emote>();var fragments=Protocol.Items(Protocol.Get(e,"message.fragments"));if(fragments!=null)foreach(var part in fragments){string name=Protocol.Pick(part,"text"),id=Protocol.Pick(part,"emote.id");if(name!=""&&System.Text.RegularExpressions.Regex.IsMatch(id,"^(?:[0-9]+|emotesv2_[a-fA-F0-9]+)$"))result.Add(new Emote{Name=name,Url="https://static-cdn.jtvnw.net/emoticons/v2/"+id+"/default/dark/2.0"});}var positions=Protocol.Items(Protocol.Get(e,"message.emotes"));string text=Protocol.Pick(e,"message.text");if(positions!=null)foreach(var emote in positions){int start,end;string id=Protocol.Pick(emote,"id");if(int.TryParse(Protocol.Pick(emote,"begin"),out start)&&int.TryParse(Protocol.Pick(emote,"end"),out end)&&start>=0&&end>=start&&end<text.Length&&System.Text.RegularExpressions.Regex.IsMatch(id,"^(?:[0-9]+|emotesv2_[a-fA-F0-9]+)$"))result.Add(new Emote{Name=text.Substring(start,end-start+1),Url="https://static-cdn.jtvnw.net/emoticons/v2/"+id+"/default/dark/2.0"});}return result;}
 public static Alert Parse(object root){string type=Protocol.Pick(root,"metadata.subscription_type","payload.subscription.type");object e=Protocol.Get(root,"payload.event");string kind,detail="";switch(type){case "channel.chat.message":kind="Chat";detail=Protocol.Pick(e,"message.text");break;case "channel.follow":kind="Follow";detail="Welcome to the community!";break;case "channel.subscribe":if(Protocol.Pick(e,"is_gift")=="True"||Protocol.Pick(e,"is_gift")=="true")return null;kind="Sub";detail="Tier "+Protocol.Pick(e,"tier");break;case "channel.subscription.message":kind="ReSub";detail=Protocol.Pick(e,"cumulative_months")+" months  "+Protocol.Pick(e,"message.text");break;case "channel.subscription.gift":kind="GiftBomb";detail=Protocol.Pick(e,"total")+" gifted subscriptions";break;case "channel.cheer":kind="Cheer";detail=Protocol.Pick(e,"bits")+" bits  "+Protocol.Pick(e,"message");break;case "channel.raid":kind="Raid";detail=Protocol.Pick(e,"viewers")+" viewers";break;default:return null;}DateTimeOffset stamp;if(!DateTimeOffset.TryParse(Protocol.Pick(root,"metadata.message_timestamp"),out stamp))stamp=DateTimeOffset.Now;string name=Protocol.Pick(e,"chatter_user_name","chatter_user_login","user_name","user_login","from_broadcaster_user_name");if(Protocol.Pick(e,"is_anonymous").Equals("true",StringComparison.OrdinalIgnoreCase))name="Anonymous";return new Alert{Time=stamp.ToLocalTime().ToString("yyyy-MM-dd HH:mm:ss"),Platform="Twitch",Kind=kind,Name=name==""?"Viewer":name,Detail=detail,Emotes=Emotes(e)};}
 public static bool ReconnectUrl(string value){Uri uri;return Uri.TryCreate(value,UriKind.Absolute,out uri)&&uri.Scheme=="wss"&&uri.Host=="eventsub.wss.twitch.tv"&&uri.IsDefaultPort&&uri.UserInfo=="";}
}
public sealed class DirectTwitch : IDisposable {
 public const string ClientId=""; // Owner fills in the registered Twitch client ID for release builds only; keep blank in git.
 public const string Scopes="moderator:read:followers channel:read:subscriptions bits:read user:read:chat user:write:chat";
 readonly HttpClient http;readonly Action<string> status;readonly Action<string,string> device;readonly Action<string,string> account;readonly Action<Alert> alert;readonly Action<List<Emote>> emotes;
 readonly HashSet<string> seen=new HashSet<string>();readonly Queue<string> order=new Queue<string>();
 string socketUrl="wss://eventsub.wss.twitch.tv/ws";TwitchTokens tokens;string user;DateTime nextValidation;bool disposed;
 public DirectTwitch(Action<string> status,Action<string,string> device,Action<string,string> account,Action<Alert> alert,Action<List<Emote>> emotes){this.status=status;this.device=device;this.account=account;this.alert=alert;this.emotes=emotes;http=new HttpClient(new HttpClientHandler{AllowAutoRedirect=false,UseCookies=false}){Timeout=TimeSpan.FromSeconds(20),MaxResponseContentBufferSize=4194304};}
 async Task<object> Request(string url,HttpMethod method,object body,CancellationToken ct,bool authorized){using(var req=new HttpRequestMessage(method,url)){if(authorized){req.Headers.Authorization=new AuthenticationHeaderValue("Bearer",tokens.Access);req.Headers.Add("Client-Id",ClientId);}if(body!=null)req.Content=body is Dictionary<string,string>?(HttpContent)new FormUrlEncodedContent((Dictionary<string,string>)body):new StringContent(Protocol.Json.Serialize(body),Encoding.UTF8,"application/json");using(var response=await http.SendAsync(req,ct)){if(!response.IsSuccessStatusCode)throw new TwitchApiError((int)response.StatusCode);return Protocol.Json.DeserializeObject(await response.Content.ReadAsStringAsync());}}}
 static int Number(object obj,string path,int fallback){int n;return int.TryParse(Protocol.Pick(obj,path),out n)?n:fallback;}
 void SaveTokens(object response){string access=Protocol.Pick(response,"access_token"),refresh=Protocol.Pick(response,"refresh_token");if(access==""||refresh=="")throw new TwitchSignInRequired("Twitch did not return a complete sign-in. Try again.");tokens=new TwitchTokens{Access=access,Refresh=refresh,Expires=DateTime.UtcNow.AddSeconds(Number(response,"expires_in",3600))};try{TwitchVault.Save(tokens);}catch(CryptographicException){throw new TwitchSignInRequired("Windows could not protect your sign-in. Run UniversalStream Assist from your normal Windows account and try again.");}catch(IOException){throw new TwitchSignInRequired("UniversalStream Assist could not save your sign-in. Check free disk space and folder access, then reconnect.");}catch(UnauthorizedAccessException){throw new TwitchSignInRequired("UniversalStream Assist could not save your sign-in in your Windows profile. Check folder permissions and reconnect.");}}
 async Task Refresh(CancellationToken ct){ct.ThrowIfCancellationRequested();tokens=await TokenRenewal.Twitch(true,tokens.Access);}
 async Task Validate(CancellationToken ct){using(var req=new HttpRequestMessage(HttpMethod.Get,"https://id.twitch.tv/oauth2/validate")){req.Headers.Authorization=new AuthenticationHeaderValue("OAuth",tokens.Access);using(var response=await http.SendAsync(req,ct)){if(response.StatusCode==HttpStatusCode.Unauthorized)throw new TwitchApiError(401);if(!response.IsSuccessStatusCode)throw new TwitchApiError((int)response.StatusCode);var data=Protocol.Json.DeserializeObject(await response.Content.ReadAsStringAsync());if(Protocol.Pick(data,"client_id")!=ClientId)throw new TwitchSignInRequired("This saved sign-in belongs to another app. Sign out and reconnect.");user=Protocol.Pick(data,"user_id");var granted=Protocol.Items(Protocol.Get(data,"scopes"))??new object[0];if(user==""||Scopes.Split(' ').Any(s=>!granted.Any(x=>x.ToString()==s)))throw new TwitchSignInRequired("Twitch permissions are missing. Sign out, reconnect, and approve the requested permissions.");tokens.Expires=DateTime.UtcNow.AddSeconds(Number(data,"expires_in",3600));nextValidation=DateTime.UtcNow.AddMinutes(50);account(user,Protocol.Pick(data,"login"));}}}
 async Task SignIn(CancellationToken ct){status("Opening Twitch sign-in…");var data=await Request("https://id.twitch.tv/oauth2/device",HttpMethod.Post,new Dictionary<string,string>{{"client_id",ClientId},{"scopes",Scopes}},ct,false);string code=Protocol.Pick(data,"device_code"),url=Protocol.Pick(data,"verification_uri");Uri uri;if(code==""||!Uri.TryCreate(url,UriKind.Absolute,out uri)||uri.Scheme!="https"||uri.Host!="www.twitch.tv")throw new TwitchSignInRequired("Twitch returned an invalid sign-in page.");device(Protocol.Pick(data,"user_code"),url);DateTime expiry=DateTime.UtcNow.AddSeconds(Number(data,"expires_in",600));int interval=Math.Max(1,Number(data,"interval",5));while(DateTime.UtcNow<expiry){await Task.Delay(TimeSpan.FromSeconds(interval),ct);using(var req=new HttpRequestMessage(HttpMethod.Post,"https://id.twitch.tv/oauth2/token")){req.Content=new FormUrlEncodedContent(new Dictionary<string,string>{{"client_id",ClientId},{"device_code",code},{"scopes",Scopes},{"grant_type","urn:ietf:params:oauth:grant-type:device_code"}});using(var response=await http.SendAsync(req,ct)){var result=Protocol.Json.DeserializeObject(await response.Content.ReadAsStringAsync());if(response.IsSuccessStatusCode){SaveTokens(result);return;}string error=Protocol.Pick(result,"message","error");if(error.Contains("authorization_pending"))continue;if(error.Contains("slow_down")){interval+=5;continue;}throw new TwitchSignInRequired("Twitch sign-in was declined or expired. Click Connect with Twitch to try again.");}}}throw new TwitchSignInRequired("The Twitch sign-in code expired. Click Connect with Twitch to try again.");}
 async Task EnsureToken(CancellationToken ct){if(tokens.Expires<=DateTime.UtcNow.AddMinutes(2))await Refresh(ct);bool refresh=false;try{await Validate(ct);}catch(TwitchApiError e){if(e.Code!=401)throw;refresh=true;}if(refresh){await Refresh(ct);await Validate(ct);}}
 async Task<object> Receive(ClientWebSocket ws,int timeout,CancellationToken ct){using(var deadline=CancellationTokenSource.CreateLinkedTokenSource(ct)){deadline.CancelAfter(TimeSpan.FromSeconds(timeout));using(var data=new MemoryStream()){byte[] buffer=new byte[8192];WebSocketReceiveResult frame;do{frame=await ws.ReceiveAsync(new ArraySegment<byte>(buffer),deadline.Token);if(frame.MessageType==WebSocketMessageType.Close)throw new IOException("Twitch closed the connection");if(frame.MessageType!=WebSocketMessageType.Text)throw new IOException("Unexpected Twitch frame");data.Write(buffer,0,frame.Count);if(data.Length>1048576)throw new IOException("Twitch message too large");}while(!frame.EndOfMessage);return Protocol.Json.DeserializeObject(Encoding.UTF8.GetString(data.ToArray()));}}}
 void Dispatch(object message){string type=Protocol.Pick(message,"metadata.message_type");if(type=="revocation")throw new TwitchSignInRequired("Twitch revoked an alert permission. Sign out and reconnect to restore alerts.");if(type!="notification")return;string id=Protocol.Pick(message,"metadata.message_id");if(id!=""){if(!seen.Add(id))return;order.Enqueue(id);while(order.Count>4000)seen.Remove(order.Dequeue());}var e=Protocol.Get(message,"payload.event");var images=TwitchEvents.Emotes(e);if(images.Count>0)emotes(images);var item=TwitchEvents.Parse(message);if(item!=null)alert(item);}
 async Task<Tuple<ClientWebSocket,object>> Open(string url,CancellationToken ct){var ws=new ClientWebSocket();ws.Options.KeepAliveInterval=TimeSpan.Zero;try{using(var deadline=CancellationTokenSource.CreateLinkedTokenSource(ct)){deadline.CancelAfter(TimeSpan.FromSeconds(20));await ws.ConnectAsync(new Uri(url),deadline.Token);var welcome=await Receive(ws,10,deadline.Token);if(Protocol.Pick(welcome,"metadata.message_type")!="session_welcome")throw new IOException("Twitch welcome missing");return Tuple.Create(ws,welcome);}}catch{ws.Dispose();throw;}}
 async Task Subscribe(string session,CancellationToken ct){var failed=new List<string>();foreach(string type in TwitchEvents.Types){try{await Request("https://api.twitch.tv/helix/eventsub/subscriptions",HttpMethod.Post,TwitchEvents.Subscription(type,user,session),ct,true);}catch(TwitchApiError e){if(e.Code==401)throw;if(e.Code!=403)throw;failed.Add(type.Replace("channel.",""));}}status(failed.Count==0?"Twitch connected · Listening for new alerts.":"Twitch connected · Unavailable: "+string.Join(", ",failed));}
 async Task Session(CancellationToken ct){ClientWebSocket ws=null;try{var connection=await Open(socketUrl,ct);ws=connection.Item1;int timeout=Number(connection.Item2,"payload.session.keepalive_timeout_seconds",10)+8;await Subscribe(Protocol.Pick(connection.Item2,"payload.session.id"),ct);while(!ct.IsCancellationRequested){var message=await Receive(ws,timeout,ct);if(Protocol.Pick(message,"metadata.message_type")=="session_reconnect"){string url=Protocol.Pick(message,"payload.session.reconnect_url");if(!TwitchEvents.ReconnectUrl(url))throw new IOException("Invalid Twitch reconnect address");var opening=Open(url,ct);using(var oldReads=CancellationTokenSource.CreateLinkedTokenSource(ct)){Task<object> pending=null;try{while(!opening.IsCompleted){pending=Receive(ws,timeout,oldReads.Token);var completed=await Task.WhenAny(opening,pending);if(completed==opening)break;Dispatch(await pending);pending=null;}var replacement=await opening;oldReads.Cancel();ws.Abort();if(pending!=null)try{Dispatch(await pending);}catch(OperationCanceledException){}catch(WebSocketException){}ws.Dispose();ws=replacement.Item1;timeout=Number(replacement.Item2,"payload.session.keepalive_timeout_seconds",10)+8;}catch{oldReads.Cancel();if(opening.IsCompleted&&opening.Status==TaskStatus.RanToCompletion)opening.Result.Item1.Dispose();else {var cleanup=opening.ContinueWith(t=>{if(t.Status==TaskStatus.RanToCompletion)t.Result.Item1.Dispose();});}throw;}}}else Dispatch(message);if(DateTime.UtcNow>=nextValidation||tokens.Expires<=DateTime.UtcNow.AddMinutes(2))await EnsureToken(ct);}}finally{if(ws!=null){ws.Abort();ws.Dispose();}}}
 public async Task Run(CancellationToken ct){try{tokens=TwitchVault.Read();if(tokens==null)await SignIn(ct);int failures=0;while(!ct.IsCancellationRequested){try{await EnsureToken(ct);await Session(ct);failures=0;}catch(TwitchSignInRequired){throw;}catch(OperationCanceledException){if(ct.IsCancellationRequested)break;status("Twitch connection timed out. Reconnecting…");}catch(TwitchApiError e){if(e.Code==401){tokens.Expires=DateTime.MinValue;continue;}status("Twitch connection needs a retry (HTTP "+e.Code+"). Reconnecting…");}catch(Exception){status("Twitch connection interrupted. Reconnecting…");}await Task.Delay(TimeSpan.FromSeconds(Math.Min(60,5*Math.Pow(2,Math.Min(failures++,4)))),ct);}}catch(OperationCanceledException){if(!ct.IsCancellationRequested)throw;}catch(TwitchSignInRequired e){status(e.Message);}catch(TwitchApiError e){status("Could not start Twitch sign-in (HTTP "+e.Code+"). Check that UniversalStream Assist is registered as a Public client.");}catch(Exception){status("Could not connect to Twitch. Check your internet connection and try again.");}}
 public void Dispose(){if(disposed)return;disposed=true;http.Dispose();}
}

