using System;using System.Collections.Generic;using System.Drawing;using System.IO;using System.Linq;using System.Net.Http;using System.Security.Cryptography;using System.Text;using System.Threading.Tasks;using System.Web.Script.Serialization;using System.Windows.Forms;
public class EventPreference {public bool Sound=true,Popup=true;public int Volume=80;public string File="";}
public class ExperiencePreferences {
 public int X=-1,Y=-1,Width=1380,Height=900,PopX=-1,PopY=-1,PopWidth=1050,PopHeight=480;
 public bool Sound=true,Popup=true,Top=false,PopTop=false,Compact=false,PopOpen=false,Updates=true;
 public int Filter=0,Retention=7;public string Search="";public Dictionary<string,EventPreference> Events=new Dictionary<string,EventPreference>();
}
public partial class MainWindow {
 const string ReleaseVersion="1.1.1.0";
 ExperiencePreferences preferences=new ExperiencePreferences();readonly Dictionary<string,DateTime> lastEvents=new Dictionary<string,DateTime>();
 readonly System.Windows.Forms.Timer saveTimer=new System.Windows.Forms.Timer{Interval=2000};
 readonly System.Windows.Media.MediaPlayer eventPlayer=new System.Windows.Media.MediaPlayer();
 bool closingExperience=false;
 DateTime pausedUntil=DateTime.MinValue;bool experienceReady=false,historyDirty=false;string storageError="",audioError="",updateMessage="",lastSavedPreferences="";
 static string ExperienceFolder {get{return Path.Combine(IntegratedHost.DataRoot);}}
 static readonly JavaScriptSerializer ExperienceJson=new JavaScriptSerializer{MaxJsonLength=16777216};
 static void WriteProtected(string file,string json){Directory.CreateDirectory(ExperienceFolder);var path=Path.Combine(ExperienceFolder,file);var temp=path+".tmp";File.WriteAllBytes(temp,ProtectedData.Protect(Encoding.UTF8.GetBytes(json),null,DataProtectionScope.CurrentUser));if(File.Exists(path))File.Replace(temp,path,null);else File.Move(temp,path);}
 static string ReadProtected(string file){return Encoding.UTF8.GetString(ProtectedData.Unprotect(File.ReadAllBytes(Path.Combine(ExperienceFolder,file)),null,DataProtectionScope.CurrentUser));}
 static string Category(string kind){switch(kind){case "Sub":case "Subscription":case "NewSubscriber":return "Subscriptions";case "ReSub":case "Resubscription":return "Resubscriptions";case "GiftSub":case "GiftSubscription":case "GiftBomb":case "MassGiftSubscription":return "Gift subscriptions";case "Cheer":return "Bits";case "Donation":case "Tip":case "CharityDonation":return "Tips";case "Follow":return "Follows";case "Raid":return "Raids";case "SuperChat":case "SuperSticker":return "Super Chats and Stickers";case "NewSponsor":case "MemberMileStone":case "MembershipGift":case "GiftMembershipReceived":return "Memberships";case "KicksGifted":case "JewelsGifted":return "Kicks and gifts";default:return "Other";}}
 EventPreference EventRule(string kind){var key=Category(kind);EventPreference rule;if(!preferences.Events.TryGetValue(key,out rule)){rule=new EventPreference();preferences.Events[key]=rule;}return rule;}
 void InitExperience(){
  try{if(File.Exists(Path.Combine(ExperienceFolder,"preferences.bin")))preferences=ExperienceJson.Deserialize<ExperiencePreferences>(ReadProtected("preferences.bin"))??new ExperiencePreferences();}catch{storageError="Saved preferences could not be read.";}
  if(preferences.Events==null)preferences.Events=new Dictionary<string,EventPreference>();preferences.Retention=new[]{0,1,7,30}.Contains(preferences.Retention)?preferences.Retention:7;
  sound.Checked=preferences.Sound;desktop.Checked=preferences.Popup;TopMost=preferences.Top;filter.SelectedIndex=Math.Max(0,Math.Min(filter.Items.Count-1,preferences.Filter));search.Text=preferences.Search??"";
  RestoreBoundsSafe(this,preferences.X,preferences.Y,preferences.Width,preferences.Height);
  try{if(preferences.Retention>0&&File.Exists(Path.Combine(ExperienceFolder,"history.bin"))){var saved=ExperienceJson.Deserialize<List<Alert>>(ReadProtected("history.bin"));if(saved!=null)alerts.AddRange(saved.Where(a=>a!=null&&!a.Demo&&a.Time!=null&&a.Name!=null&&a.Detail!=null&&a.Kind!=null&&a.Platform!=null).Take(2000));}}catch{storageError="Saved history could not be read. The original file has been kept.";}
  TrimHistory();foreach(var a in alerts){DateTime time;if(DateTime.TryParse(a.Time,out time)&&(!lastEvents.ContainsKey(a.Platform)||lastEvents[a.Platform]<time))lastEvents[a.Platform]=time;PrepareMessage(a);}RefreshFeed();ApplyCompact();
  var menu=new ContextMenuStrip();menu.Items.Add("Replay notification",null,delegate{if(feed.SelectedItems.Count>0){lastSound=DateTime.MinValue;NotifyDesktop((Alert)feed.SelectedItems[0].Tag);}});menu.Items.Add("View details",null,delegate{ShowSelectedAlert();});feed.ContextMenuStrip=menu;
  feed.MouseDown+=delegate(object sender,MouseEventArgs e){if(e.Button==MouseButtons.Right){var item=feed.GetItemAt(e.X,e.Y);if(item!=null){feed.SelectedItems.Clear();item.Selected=true;}}};
  eventPlayer.MediaFailed+=delegate{audioError="Could not play the selected sound. Choose another WAV file.";};
  saveTimer.Tick+=delegate{SaveExperience();};saveTimer.Start();experienceReady=true;
  FormClosing+=delegate{SaveExperience();saveTimer.Stop();eventPlayer.Close();};FormClosed+=delegate{saveTimer.Dispose();menu.Dispose();};
  Shown+=async delegate{if(preferences.PopOpen)PopOutAlerts();if(preferences.Updates&&!IntegratedHost.Active)await CheckRelease(false);};
 }
 static void RestoreBoundsSafe(Form w,int x,int y,int width,int height){if(x<0&&y<0)return;var rect=new Rectangle(x,y,Math.Max(w.MinimumSize.Width,Math.Min(2400,width)),Math.Max(w.MinimumSize.Height,Math.Min(1600,height)));if(Screen.AllScreens.Any(s=>Rectangle.Intersect(s.WorkingArea,rect).Width>=150&&Rectangle.Intersect(s.WorkingArea,rect).Height>=100)){w.StartPosition=FormStartPosition.Manual;w.Bounds=rect;}}
 void TrimHistory(){if(preferences.Retention<=0)return;DateTime threshold=DateTime.Now.AddDays(-preferences.Retention);alerts.RemoveAll(a=>!a.Demo&&!RecentAlert(a,threshold));}
 static bool RecentAlert(Alert a,DateTime threshold){DateTime time;return DateTime.TryParse(a.Time,out time)&&time>=threshold;}
 void SaveExperience(){if(!experienceReady)return;try{var r=WindowState==FormWindowState.Normal?Bounds:RestoreBounds;preferences.X=r.X;preferences.Y=r.Y;preferences.Width=r.Width;preferences.Height=r.Height;preferences.Sound=sound.Checked;preferences.Popup=desktop.Checked;preferences.Top=TopMost;preferences.Filter=filter.SelectedIndex;preferences.Search=search.Text;if(alertsWindow!=null)CapturePopout(alertsWindow);string settingsJson=ExperienceJson.Serialize(preferences);if(settingsJson!=lastSavedPreferences){WriteProtected("preferences.bin",settingsJson);lastSavedPreferences=settingsJson;}int before=alerts.Count;TrimHistory();if(alerts.Count!=before){historyDirty=true;RefreshFeed();}if(historyDirty){WriteProtected("history.bin",ExperienceJson.Serialize(preferences.Retention==0?new List<Alert>():alerts.Where(a=>!a.Demo).Take(2000).ToList()));historyDirty=false;}storageError="";}catch{storageError="Settings or history could not be saved. Check available disk space.";}}
 void RecordArrival(Alert a){if(!a.Demo){lastEvents[a.Platform]=DateTime.Now;historyDirty=true;}}
 void CapturePopout(Form w){var r=w.WindowState==FormWindowState.Normal?w.Bounds:w.RestoreBounds;preferences.PopX=r.X;preferences.PopY=r.Y;preferences.PopWidth=r.Width;preferences.PopHeight=r.Height;preferences.PopTop=w.TopMost;}
 void SetupPopout(Form w,CheckBox pin){RestoreBoundsSafe(w,preferences.PopX,preferences.PopY,preferences.PopWidth,preferences.PopHeight);pin.Checked=preferences.PopTop;preferences.PopOpen=true;w.MinimumSize=new Size(preferences.Compact?500:760,260);w.FormClosing+=delegate{CapturePopout(w);if(!closingExperience)preferences.PopOpen=false;};}
 void ApplyCompact(){if(feed.Columns.Count<5)return;if(alertsWindow!=null)alertsWindow.MinimumSize=new Size(preferences.Compact?500:760,260);if(preferences.Compact){if(feed.Font.Size!=12){var old=feed.Font;feed.Font=new Font("Segoe UI",12);old.Dispose();}feed.Columns[0].Width=0;feed.Columns[1].Width=0;feed.Columns[2].Width=160;feed.Columns[3].Width=150;feed.Columns[4].Width=Math.Max(180,feed.ClientSize.Width-315);}else{if(feed.Font.Size!=11){var old=feed.Font;feed.Font=new Font("Segoe UI",11);old.Dispose();}int width=feed.ClientSize.Width;feed.Columns[0].Width=78;feed.Columns[1].Width=92;feed.Columns[2].Width=185;feed.Columns[3].Width=120;feed.Columns[4].Width=Math.Max(170,width-479);}}
 void PlayEventSound(Alert alert){var rule=EventRule(alert.Kind);if(!sound.Checked||!rule.Sound||rule.Volume<=0||DateTime.UtcNow<pausedUntil||(DateTime.UtcNow-lastSound).TotalSeconds<1)return;lastSound=DateTime.UtcNow;string path=string.IsNullOrEmpty(rule.File)?SoundPreferences.Read():rule.File;try{if(!File.Exists(path))path=SoundPreferences.DefaultPath;eventPlayer.Stop();eventPlayer.Open(new Uri(Path.GetFullPath(path)));eventPlayer.Volume=Math.Max(0,Math.Min(100,rule.Volume))/100.0;eventPlayer.Play();audioError="";}catch{audioError="Notification sound unavailable. Choose another WAV file.";}}
 bool ShowEventPopup(Alert a){return desktop.Checked&&EventRule(a.Kind).Popup;}
 void ShowExperience(){using(var w=new Form{Text="Alert preferences",Size=new Size(800,690),MinimumSize=new Size(760,600),StartPosition=FormStartPosition.CenterParent,BackColor=Theme.Canvas,ForeColor=Theme.Text,Font=Font}){
 var panel=new FlowLayoutPanel{Dock=DockStyle.Fill,FlowDirection=FlowDirection.TopDown,WrapContents=false,AutoScroll=true,Padding=new Padding(20)};w.Controls.Add(panel);
 var compact=new CheckBox{Text="Compact alerts — viewer, activity and message",AutoSize=true,Checked=preferences.Compact};compact.CheckedChanged+=delegate{preferences.Compact=compact.Checked;ApplyCompact();};panel.Controls.Add(compact);
 var retention=new ComboBox{DropDownStyle=ComboBoxStyle.DropDownList,Width=350};retention.Items.AddRange(new object[]{"Do not save history","Keep history for 1 day","Keep history for 7 days","Keep history for 30 days"});retention.SelectedIndex=Array.IndexOf(new[]{0,1,7,30},preferences.Retention);panel.Controls.Add(new Label{Text="History (up to 2,000 alerts, protected on this Windows account)",AutoSize=true});panel.Controls.Add(retention);retention.SelectedIndexChanged+=delegate{preferences.Retention=new[]{0,1,7,30}[retention.SelectedIndex];historyDirty=true;SaveExperience();RefreshFeed();};
 var row=new FlowLayoutPanel{Width=710,Height=50};row.Controls.Add(Button("Delete saved history",delegate{if(MessageBox.Show(w,"Delete all alerts and saved history?","Delete history",MessageBoxButtons.YesNo)==DialogResult.Yes){alerts.Clear();cleared.Clear();historyDirty=true;SaveExperience();RefreshFeed();}}));row.Controls.Add(Button("Pause sounds 15 min",delegate{pausedUntil=DateTime.UtcNow.AddMinutes(15);}));row.Controls.Add(Button("Resume sounds",delegate{pausedUntil=DateTime.MinValue;}));panel.Controls.Add(row);
 panel.Controls.Add(new Label{Text="Event sound and desktop pop-up rules",AutoSize=true});var kinds=new[]{"Follow","Subscription","Resubscription","GiftSubscription","Cheer","Tip","Raid","SuperChat","NewSponsor","KicksGifted","Other"};
 var choose=new ComboBox{DropDownStyle=ComboBoxStyle.DropDownList,Width=350};choose.Items.AddRange(kinds.Select(Category).Cast<object>().ToArray());panel.Controls.Add(choose);var enableSound=new CheckBox{Text="Play sound for this event",AutoSize=true};var enablePopup=new CheckBox{Text="Show desktop pop-up for this event",AutoSize=true};var volume=new TrackBar{Minimum=0,Maximum=100,TickFrequency=10,Width=450};var volumeLabel=new Label{AutoSize=true};var fileLabel=new Label{Width=680,Height=40};panel.Controls.Add(enableSound);panel.Controls.Add(enablePopup);panel.Controls.Add(volumeLabel);panel.Controls.Add(volume);panel.Controls.Add(fileLabel);bool loading=false;Action load=delegate{loading=true;var rule=EventRule(kinds[choose.SelectedIndex]);enableSound.Checked=rule.Sound;enablePopup.Checked=rule.Popup;volume.Value=Math.Max(0,Math.Min(100,rule.Volume));volumeLabel.Text="Volume: "+volume.Value+"%";fileLabel.Text=string.IsNullOrEmpty(rule.File)?"Sound: default chime":"Sound: "+Path.GetFileName(rule.File);loading=false;};choose.SelectedIndexChanged+=delegate{load();};choose.SelectedIndex=0;enableSound.CheckedChanged+=delegate{if(!loading)EventRule(kinds[choose.SelectedIndex]).Sound=enableSound.Checked;};enablePopup.CheckedChanged+=delegate{if(!loading)EventRule(kinds[choose.SelectedIndex]).Popup=enablePopup.Checked;};volume.ValueChanged+=delegate{volumeLabel.Text="Volume: "+volume.Value+"%";if(!loading)EventRule(kinds[choose.SelectedIndex]).Volume=volume.Value;};
 var sounds=new FlowLayoutPanel{Width=710,Height=50};sounds.Controls.Add(Button("Choose WAV",delegate{using(var pick=new OpenFileDialog{Filter="WAV audio|*.wav"})if(pick.ShowDialog(w)==DialogResult.OK)try{using(var check=SoundPreferences.Load(pick.FileName)){}EventRule(kinds[choose.SelectedIndex]).File=pick.FileName;load();}catch(Exception ex){MessageBox.Show(w,ex.Message);}}));sounds.Controls.Add(Button("Use default",delegate{EventRule(kinds[choose.SelectedIndex]).File="";load();}));sounds.Controls.Add(Button("Test event",delegate{lastSound=DateTime.MinValue;NotifyDesktop(new Alert{Kind=kinds[choose.SelectedIndex],Platform="Preview",Name="Sample viewer",Detail="Notification preview",Demo=true});}));panel.Controls.Add(sounds);
 var updates=new CheckBox{Text="Check for new versions when the app starts",AutoSize=true,Checked=preferences.Updates};updates.CheckedChanged+=delegate{preferences.Updates=updates.Checked;};panel.Controls.Add(updates);panel.Controls.Add(Button("Check for updates",async delegate{await CheckRelease(true);}));var info=new Label{Width=700,Height=65};panel.Controls.Add(info);var timer=new System.Windows.Forms.Timer{Interval=500};timer.Tick+=delegate{info.Text=(DateTime.UtcNow<pausedUntil?"Sounds paused until "+pausedUntil.ToLocalTime().ToShortTimeString()+". ":"")+storageError+" "+audioError;};timer.Start();try{w.ShowDialog(this);}finally{timer.Dispose();SaveExperience();}}}
 void ShowConnectionHealth(){using(var w=new Form{Text="Connection health",Size=new Size(790,430),StartPosition=FormStartPosition.CenterParent,BackColor=Theme.Canvas,ForeColor=Theme.Text,Font=Font}){var text=new Label{Dock=DockStyle.Fill,Padding=new Padding(24)};w.Controls.Add(text);Action refresh=delegate{text.Text=string.Join("\n\n",new[]{"Twitch","YouTube","Kick","Streamlabs"}.Select(name=>{DateTime last;string value=name=="Twitch"?twitchStatus:name=="YouTube"?youtubeStatus:name=="Kick"?kickStatus:streamlabsStatus;return value+"\nLast received event: "+(lastEvents.TryGetValue(name,out last)?last.ToString("g"):"None yet");}));};refresh();var timer=new System.Windows.Forms.Timer{Interval=1000};timer.Tick+=delegate{refresh();};timer.Start();try{w.ShowDialog(this);}finally{timer.Dispose();}}}
 async Task CheckRelease(bool explicitCheck){if(IntegratedHost.Active){if(explicitCheck)MessageBox.Show("UniversalCollab Private 1.2.0-preview.1. Update the combined application as a complete package.","Combined app version");return;}try{using(var client=new HttpClient(new HttpClientHandler{AllowAutoRedirect=false}){Timeout=TimeSpan.FromSeconds(10)}){var json=await client.GetStringAsync("https://assist-beta.universalcollab.stream/desktop-release");var data=ExperienceJson.DeserializeObject(json);Version latest;if(!Version.TryParse(Protocol.Pick(data,"version"),out latest))throw new IOException();if(latest>new Version(ReleaseVersion)){updateMessage="Version "+latest+" is available.\n\n"+Protocol.Pick(data,"notes")+"\n\nContact the beta operator for the new download.";MessageBox.Show(updateMessage,"App update available");}else if(explicitCheck)MessageBox.Show("You have the latest published version ("+ReleaseVersion+").","Updates");}}catch{if(explicitCheck)MessageBox.Show("Could not check for updates. Try again later.","Updates");}}
}
