using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Net.WebSockets;
using System.Security.Cryptography;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using System.Web.Script.Serialization;
using System.Windows.Forms;

[assembly: System.Runtime.Versioning.TargetFramework(".NETFramework,Version=v4.8")]

public class Alert {
 public string Time, Platform, Kind, Name, Detail;
 [ScriptIgnore] public string ChatId=Guid.NewGuid().ToString("N");[ScriptIgnore] public long ChatReceived=DateTimeOffset.UtcNow.ToUnixTimeMilliseconds();
 public bool Demo; [ScriptIgnore] public List<MessageRun> Runs=new List<MessageRun>();
 public List<Emote> Emotes=new List<Emote>();
}
public class Emote { public string Name,Url; }
public static class Protocol {
 public static JavaScriptSerializer Json = new JavaScriptSerializer { MaxJsonLength = 1048576 };
 public static object Get(object o, string path) { foreach(var k in path.Split('.')) { var d=o as Dictionary<string,object>; if(d==null || !d.TryGetValue(k,out o)) return null; } return o; }
 public static object[] Items(object value){var list=value as System.Collections.IList;return list==null?null:list.Cast<object>().ToArray();}
 public static string Pick(object o, params string[] paths) { foreach(var p in paths) { var v=Get(o,p); if(v!=null && !(v is Dictionary<string,object>) && !(v is System.Collections.IList) && v.ToString()!="") return v.ToString(); } return ""; }
 public static bool Supported(string source,string type) {
  if(!new[]{"twitch","youtube","kick","streamlabs","streamelements","kofi"}.Contains(source.ToLowerInvariant())) return false;
  return new[]{"Follow","Sub","ReSub","GiftSub","GiftBomb","Cheer","Raid","Subscription","Resubscription","GiftSubscription","MassGiftSubscription","KicksGifted","SuperChat","SuperSticker","NewSponsor","NewSubscriber","MemberMileStone","MembershipGift","GiftMembershipReceived","JewelsGifted","Donation","Tip","CharityDonation"}.Contains(type);
 }
 public static Alert Parse(object root) {
  string s=Pick(root,"event.source"), t=Pick(root,"event.type"); if(!Supported(s,t)) return null;
  object d=Get(root,"data");
  string name=Pick(d,"targetUser.name","targetUser.login","user.name","user.displayName","from.name","gifter.name","sender.name","donation.name","name","displayName","userName","username","user.login");
  if(Pick(d,"anonymous","isAnonymous").Equals("true",StringComparison.OrdinalIgnoreCase)) name="Anonymous";
  if(name=="") name="Viewer";
  string amount=Pick(d,"amountFormatted","formattedAmount","amount","decimalAmount","donation.amount"), currency=Pick(d,"currency","currencyCode","donation.currency");
  string detail=Pick(d,"text","message.text","message","comment","donation.message");
  string bits=Pick(d,"bits"), count=Pick(d,"gifts","count","giftCount","months","cumulativeMonths","duration","viewers");
  if(bits!="") detail=bits+" bits  "+detail;
  if(amount!="") detail=amount+" "+currency+"  "+detail;
  if(count!="") detail="Count: "+count+"  "+detail;
  DateTimeOffset stamp; if(!DateTimeOffset.TryParse(Pick(root,"timeStamp","timestamp"),out stamp)) stamp=DateTimeOffset.Now;
  return new Alert {Time=stamp.ToLocalTime().ToString("yyyy-MM-dd HH:mm:ss"),Platform=s,Kind=t,Name=name,Detail=detail.Trim(),Demo=Pick(d,"isTest","meta.isTest").Equals("true",StringComparison.OrdinalIgnoreCase),Emotes=ReadEmotes(d)};
 }
 public static List<Emote> ReadEmotes(object data){var result=new List<Emote>();string message=Pick(data,"text","message.text","message","comment");foreach(string path in new[]{"emotes","cheerEmotes","message.emotes","parts","message.parts"}){var items=Items(Get(data,path));if(items==null)continue;foreach(var item in items){string url=Pick(item,"ImageUrl","imageUrl","url","emote.imageUrl","cheermote.imageUrl"),name=Pick(item,"Name","name","text","code");int start,end;if(name==""&&int.TryParse(Pick(item,"StartIndex","startIndex"),out start)&&int.TryParse(Pick(item,"EndIndex","endIndex"),out end)&&start>=0&&end>=start&&end<message.Length)name=message.Substring(start,end-start+1);if(url.StartsWith("//"))url="https:"+url;if(url==""){string id=Pick(item,"id","Id","emote.id"),source=Pick(item,"source","Source");if(System.Text.RegularExpressions.Regex.IsMatch(id,"^(?:[0-9]+|emotesv2_[a-fA-F0-9]+)$")&&(source==""||source.Equals("twitch",StringComparison.OrdinalIgnoreCase)))url="https://static-cdn.jtvnw.net/emoticons/v2/"+id+"/default/dark/2.0";}if(url==""||name==""||result.Any(x=>x.Url==url&&x.Name==name))continue;result.Add(new Emote{Name=name,Url=url});if(result.Count==128)return result;}}return result;}
 public static string Hash(string s) { using(var h=SHA256.Create()) return Convert.ToBase64String(h.ComputeHash(Encoding.UTF8.GetBytes(s))); }
}
public static class Theme {
 public static readonly Color Canvas=Color.FromArgb(22,15,37);
 public static readonly Color Surface=Color.FromArgb(37,25,55);
 public static readonly Color Raised=Color.FromArgb(61,41,86);
 public static readonly Color Text=Color.FromArgb(247,240,255);
 public static readonly Color Muted=Color.FromArgb(185,169,205);
 public static readonly Color Accent=Color.FromArgb(200,163,255);
 public static void Round(Control c,int radius) {c.Resize+=delegate{if(c.Width<radius||c.Height<radius)return;using(var path=new System.Drawing.Drawing2D.GraphicsPath()){int d=radius;path.AddArc(0,0,d,d,180,90);path.AddArc(c.Width-d,0,d,d,270,90);path.AddArc(c.Width-d,c.Height-d,d,d,0,90);path.AddArc(0,c.Height-d,d,d,90,90);path.CloseFigure();var old=c.Region;c.Region=new Region(path);if(old!=null)old.Dispose();}};}
}
public class ModernButton : Button {
 public bool Primary;
 bool hovered,pressed;
 public ModernButton(){SetStyle(ControlStyles.UserPaint|ControlStyles.AllPaintingInWmPaint|ControlStyles.OptimizedDoubleBuffer|ControlStyles.ResizeRedraw,true);UseVisualStyleBackColor=false;}
 protected override void OnPaintBackground(PaintEventArgs e){e.Graphics.Clear(Parent==null?Theme.Canvas:Parent.BackColor);}
 protected override void OnMouseEnter(EventArgs e){base.OnMouseEnter(e);hovered=true;Invalidate();}
 protected override void OnMouseLeave(EventArgs e){base.OnMouseLeave(e);hovered=false;pressed=false;Invalidate();}
 protected override void OnMouseDown(MouseEventArgs e){base.OnMouseDown(e);if(e.Button==MouseButtons.Left)pressed=true;Invalidate();}
 protected override void OnMouseUp(MouseEventArgs e){base.OnMouseUp(e);pressed=false;Invalidate();}
 protected override void OnGotFocus(EventArgs e){base.OnGotFocus(e);Invalidate();}
 protected override void OnLostFocus(EventArgs e){base.OnLostFocus(e);pressed=false;Invalidate();}
 protected override void OnPaint(PaintEventArgs e) {
  e.Graphics.Clear(Parent==null?Theme.Canvas:Parent.BackColor);
  e.Graphics.SmoothingMode=System.Drawing.Drawing2D.SmoothingMode.AntiAlias;
  var r=new Rectangle(1,1,Width-3,Height-3);int radius=18;
  using(var p=new System.Drawing.Drawing2D.GraphicsPath()){
   p.AddArc(r.X,r.Y,radius,radius,180,90);p.AddArc(r.Right-radius,r.Y,radius,radius,270,90);p.AddArc(r.Right-radius,r.Bottom-radius,radius,radius,0,90);p.AddArc(r.X,r.Bottom-radius,radius,radius,90,90);p.CloseFigure();
   using(var b=new SolidBrush(Enabled&&!pressed?BackColor:Theme.Surface))e.Graphics.FillPath(b,p);
   if(Focused||Primary||hovered)using(var pen=new Pen(Theme.Accent,Focused?2:1))e.Graphics.DrawPath(pen,p);
  }
  TextRenderer.DrawText(e.Graphics,Text,Font,r,Enabled?ForeColor:Color.Gray,TextFormatFlags.HorizontalCenter|TextFormatFlags.VerticalCenter|TextFormatFlags.EndEllipsis|TextFormatFlags.NoPrefix);
 }
}
public partial class MainWindow : Form {
 CancellationTokenSource twitchStop; Task twitchTask; string twitchStatus="Twitch: not connected"; Form twitchLogin; readonly System.Windows.Forms.Timer connectionTimer=new System.Windows.Forms.Timer{Interval=400}; Button bridgeButton=new Button();
 readonly Color bg=Theme.Canvas, panel=Theme.Surface, muted=Theme.Muted, accent=Theme.Accent;
 TextBox endpoint=new TextBox(), password=new TextBox(), search=new TextBox();
 Label status=new Label(), totals=new Label(), empty=new Label(), summary=new Label();
 Button connect=new Button(); ComboBox filter=new ComboBox(); CheckBox sound=new CheckBox(),desktop=new CheckBox();
 readonly EmoteCache emoteCache=new EmoteCache(); readonly SevenTvCatalog sevenTv=new SevenTvCatalog(); readonly System.Windows.Forms.Timer emoteAnimation=new System.Windows.Forms.Timer{Interval=80}; readonly System.Windows.Forms.Timer emoteRefresh=new System.Windows.Forms.Timer{Interval=300000}; string detectedChannel="36540809"; string emoteSetOverride=""; DesktopAlert popup; NotifyIcon tray; System.Media.SoundPlayer chime; DateTime lastSound=DateTime.MinValue; bool previewing;
 ListView feed=new BufferedFeed(); List<Alert> alerts=new List<Alert>(), cleared=new List<Alert>(); CancellationTokenSource stop;
 HashSet<string> seen=new HashSet<string>(); Queue<string> seenOrder=new Queue<string>();
 public MainWindow() {
  Text="UniversalCollab · Stream Assist";Icon=Icon.ExtractAssociatedIcon(Application.ExecutablePath);Size=new Size(1380,900);MinimumSize=new Size(1120,790);StartPosition=FormStartPosition.CenterScreen;BackColor=bg;ForeColor=Color.White;Font=new Font("Segoe UI",11);AutoScaleMode=AutoScaleMode.Dpi;
  endpoint.Text="ws://127.0.0.1:8080/";password.UseSystemPasswordChar=true;endpoint.BackColor=password.BackColor=Theme.Raised;endpoint.ForeColor=password.ForeColor=Theme.Text;endpoint.BorderStyle=password.BorderStyle=BorderStyle.FixedSingle;
  var root=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=2,RowCount=1,Padding=new Padding(0)};root.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,235));root.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));Controls.Add(root);
  var side=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=1,RowCount=11,Padding=new Padding(22,28,18,22),BackColor=panel,Margin=new Padding(0)};
  foreach(int h in new[]{86,54,54,54,54,54,54,54})side.RowStyles.Add(new RowStyle(SizeType.Absolute,h));side.RowStyles.Add(new RowStyle(SizeType.Percent,100));side.RowStyles.Add(new RowStyle(SizeType.Absolute,48));side.RowStyles.Add(new RowStyle(SizeType.Absolute,60));root.Controls.Add(side,0,0);
  side.Controls.Add(Label("UniversalStream\nAssist",17,Theme.Text,true),0,0);
  side.Controls.Add(Button("Activity",delegate{feed.Focus();},true),0,1);
  side.Controls.Add(Button("Connections",delegate{ShowAccounts();}),0,2);
  side.Controls.Add(Button("Notifications",delegate{ShowNotificationPreferences();}),0,3);
  side.Controls.Add(Button("Emotes",delegate{ShowSevenTv();}),0,4);
  side.Controls.Add(Button("Combined chat",delegate{ShowCombinedChat();}),0,5);side.Controls.Add(Button("Alert preferences",delegate{ShowExperience();}),0,6);
  side.Controls.Add(Button("Integrations",delegate{ShowIntegrations();}),0,7);
  side.Controls.Add(Button("Help & setup",delegate{ShowGuide();}),0,9);
  side.Controls.Add(Label("PRIVATE EDITION\nYour streams. One place.",9,muted,false),0,10);
  foreach(Control item in side.Controls){var button=item as Button;if(button==null)continue;button.AutoSize=false;button.Dock=DockStyle.Fill;button.Margin=new Padding(0,5,0,5);}
  var main=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=1,RowCount=9,Padding=new Padding(28,22,24,14)};foreach(int h in new[]{60,42,220,45,46,16})main.RowStyles.Add(new RowStyle(SizeType.Absolute,h));main.RowStyles.Add(new RowStyle(SizeType.Percent,100));main.RowStyles.Add(new RowStyle(SizeType.Absolute,56));main.RowStyles.Add(new RowStyle(SizeType.Absolute,44));root.Controls.Add(main,1,0);
  var heading=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=2,RowCount=1};heading.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));heading.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,185));main.Controls.Add(heading,0,0);heading.Controls.Add(Label("Every moment, together.",25,Theme.Text,true),0,0);var preview=Button("Try sample alerts",delegate{Samples();},true);preview.Dock=DockStyle.Fill;preview.Margin=new Padding(4,8,0,8);heading.Controls.Add(preview,1,0);
  main.Controls.Add(Label("Your community, across every stream.",11,muted,false),0,1);
  var cards=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=4,RowCount=1,Margin=new Padding(0,0,0,12)};for(int i=0;i<4;i++)cards.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,25));main.Controls.Add(cards,0,2);
  AddServiceCard(cards,0,"Twitch","Follows, subscriptions,\nbits and raids.",()=>twitchStatus);
  AddServiceCard(cards,1,"YouTube","Super Chats and live\nmembership moments.",()=>youtubeStatus);
  AddServiceCard(cards,2,"Kick","Follows, subscriptions\nand Kicks.",()=>kickStatus);
  AddServiceCard(cards,3,"Streamlabs","Tips and messages\nfrom your supporters.",()=>streamlabsStatus);
  status=Label("Bridge: not connected",10,accent,false);connectionTimer.Start();
  summary=Label("No alerts yet",12,Color.White,true);summary.Padding=new Padding(0,12,0,0);main.Controls.Add(summary,0,3);
  var toolbar=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=4,RowCount=1};toolbar.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,65));toolbar.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,170));toolbar.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,70));toolbar.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));main.Controls.Add(toolbar,0,4);
  toolbar.Controls.Add(Label("Filter",10,muted,false),0,0);filter.DropDownStyle=ComboBoxStyle.DropDownList;filter.Items.AddRange(new object[]{"All platforms","Twitch","YouTube","Kick","Streamlabs","StreamElements","Kofi"});filter.SelectedIndex=0;filter.Dock=DockStyle.Fill;filter.SelectedIndexChanged+=delegate{RefreshFeed();};toolbar.Controls.Add(filter,1,0);
  toolbar.Controls.Add(Label("Search",10,muted,false),2,0);search.Dock=DockStyle.Fill;search.AccessibleName="Search alerts by viewer, event or message";search.TextChanged+=delegate{RefreshFeed();};toolbar.Controls.Add(search,3,0);
  filter.DrawMode=DrawMode.OwnerDrawFixed;filter.ItemHeight=25;filter.DrawItem+=delegate(object sender,DrawItemEventArgs e){using(var b=new SolidBrush(panel))e.Graphics.FillRectangle(b,e.Bounds);if(e.Index>=0)TextRenderer.DrawText(e.Graphics,filter.Items[e.Index].ToString(),Font,new Rectangle(e.Bounds.X+8,e.Bounds.Y,e.Bounds.Width-8,e.Bounds.Height),Color.White,TextFormatFlags.VerticalCenter);};filter.FlatStyle=FlatStyle.Flat;filter.BackColor=panel;filter.ForeColor=Color.White;search.BorderStyle=BorderStyle.FixedSingle;search.BackColor=panel;search.ForeColor=Color.White;
  sound.Text="Notification sound";sound.AutoSize=true;sound.Checked=true;desktop.Text="Desktop pop-ups";desktop.AutoSize=true;desktop.Checked=true;
  var feedArea=new Panel{Dock=DockStyle.Fill,BackColor=panel};main.Controls.Add(feedArea,0,6);Theme.Round(feedArea,18);
  feed.Dock=DockStyle.Fill;feed.View=View.Details;feed.FullRowSelect=true;feed.BackColor=panel;feed.ForeColor=Color.White;feed.BorderStyle=BorderStyle.None;feed.HeaderStyle=ColumnHeaderStyle.Nonclickable;feed.Font=new Font("Segoe UI",11);feed.HideSelection=false;
  foreach(var c in new[]{Tuple.Create("Time",90),Tuple.Create("Platform",106),Tuple.Create("Activity",244),Tuple.Create("Viewer",145),Tuple.Create("Details",280)})feed.Columns.Add(c.Item1,c.Item2);
  feed.Resize+=delegate{if(feed.Columns.Count==5){int available=feed.ClientSize.Width-4;feed.Columns[0].Width=78;feed.Columns[1].Width=92;feed.Columns[2].Width=available<900?185:220;feed.Columns[3].Width=available<900?120:145;feed.Columns[4].Width=Math.Max(170,available-feed.Columns[0].Width-feed.Columns[1].Width-feed.Columns[2].Width-feed.Columns[3].Width);}};feed.Resize+=delegate{ApplyCompact();};feed.OwnerDraw=true;feed.DrawColumnHeader+=delegate(object sender,DrawListViewColumnHeaderEventArgs e){using(var b=new SolidBrush(Theme.Raised))e.Graphics.FillRectangle(b,e.Bounds);TextRenderer.DrawText(e.Graphics,e.Header.Text,Font,new Rectangle(e.Bounds.X+10,e.Bounds.Y,e.Bounds.Width-12,e.Bounds.Height),muted,TextFormatFlags.VerticalCenter|TextFormatFlags.EndEllipsis);};
  feed.DrawItem+=delegate(object sender,DrawListViewItemEventArgs e){};
  feed.DrawSubItem+=delegate(object sender,DrawListViewSubItemEventArgs e){Color row=e.Item.Selected?Theme.Raised:(e.ItemIndex%2==0?panel:Theme.Canvas);using(var b=new SolidBrush(row))e.Graphics.FillRectangle(b,e.Bounds);var rect=new Rectangle(e.Bounds.X+10,e.Bounds.Y,e.Bounds.Width-14,e.Bounds.Height);Color ink=e.ColumnIndex==1?e.Item.ForeColor:e.ColumnIndex==0?muted:Theme.Text;if(e.ColumnIndex==2){var alert=e.Item.Tag as Alert;if(alert!=null){e.Graphics.DrawImage(ActionIcons.Get(alert.Kind),new Rectangle(rect.X,rect.Y+(rect.Height-26)/2,26,26));rect.X+=34;rect.Width-=34;}}if(e.ColumnIndex==4){var item=e.Item.Tag as Alert;if(item!=null){rect.Y+=(rect.Height-32)/2;rect.Height=32;InlineMessage.Draw(e.Graphics,Font,ink,rect,item.Runs,emoteCache,false);return;}}TextRenderer.DrawText(e.Graphics,e.SubItem.Text,Font,rect,ink,TextFormatFlags.VerticalCenter|TextFormatFlags.EndEllipsis|TextFormatFlags.NoPrefix);};
  var rowHeight=new ImageList{ImageSize=new Size(1,44)};feed.SmallImageList=rowHeight;Disposed+=delegate{rowHeight.Dispose();};feedArea.Controls.Add(feed);
  empty=Label("Your next great moment starts here\n\nOpen Connections to sign in, or try sample alerts.",13,muted,false);empty.TextAlign=ContentAlignment.MiddleCenter;empty.BackColor=panel;feedArea.Controls.Add(empty);empty.BringToFront();
  var actions=new FlowLayoutPanel{Dock=DockStyle.Fill,Padding=new Padding(0,6,0,0)};actions.Controls.Add(Button("Health",delegate{ShowConnectionHealth();}));actions.Controls.Add(Button("Pop out alerts",delegate{PopOutAlerts();},true));actions.Controls.Add(Button("Save session",delegate{Export();}));actions.Controls.Add(Button("Clear feed",delegate{cleared=new List<Alert>(alerts);alerts.Clear();historyDirty=true;RefreshFeed();}));actions.Controls.Add(Button("Undo clear",delegate{foreach(var a in cleared)if(!alerts.Contains(a))alerts.Add(a);alerts=alerts.OrderByDescending(a=>a.Time).Take(2000).ToList();cleared.Clear();historyDirty=true;RefreshFeed();}));main.Controls.Add(actions,0,7);
  totals=Label("",9,muted,false);main.Controls.Add(totals,0,8);
  feed.DoubleClick+=delegate{ShowSelectedAlert();};feed.KeyDown+=delegate(object sender,KeyEventArgs e){if(e.KeyCode==Keys.Enter)ShowSelectedAlert();};
    popup=new DesktopAlert(Icon,RestoreWindow);desktop.CheckedChanged+=delegate{if(!desktop.Checked)popup.Hide();};
  tray=new NotifyIcon{Icon=Icon,Text="UniversalStream Assist — stream alerts",Visible=!IntegratedHost.Active};tray.DoubleClick+=delegate{RestoreWindow();};var trayMenu=new ContextMenuStrip();trayMenu.Items.Add("Open UniversalStream Assist",null,delegate{RestoreWindow();});trayMenu.Items.Add("Exit UniversalStream Assist",null,delegate{Close();});tray.ContextMenuStrip=trayMenu;
  string soundFile=SoundPreferences.Read();if(File.Exists(soundFile))chime=new System.Media.SoundPlayer(soundFile);
  emoteAnimation.Tick+=delegate{if((alertsWindow==null&&WindowState==FormWindowState.Minimized)||!feed.Visible||feed.TopItem==null)return;for(int i=feed.TopItem.Index;i<feed.Items.Count;i++){var row=feed.Items[i];if(row.Bounds.Top>=feed.ClientSize.Height)break;var alert=row.Tag as Alert;if(alert!=null&&alert.Runs.Any(r=>emoteCache.IsAnimated(r.Url)))feed.Invalidate(row.SubItems[4].Bounds);}};emoteAnimation.Start();emoteRefresh.Tick+=async delegate{await ReloadSevenTv();};emoteRefresh.Start();Shown+=async delegate{await ReloadSevenTv();};
  FormClosing+=delegate{closingExperience=true;if(alertsWindow!=null)alertsWindow.Close();if(stop!=null)stop.Cancel();if(twitchStop!=null)twitchStop.Cancel();if(streamlabsStop!=null)streamlabsStop.Cancel();if(youtubeStop!=null)youtubeStop.Cancel();if(kickStop!=null)kickStop.Cancel();};FormClosed+=delegate{connectionTimer.Dispose();tray.Visible=false;tray.Dispose();trayMenu.Dispose();popup.Dispose();sevenTv.Dispose();emoteAnimation.Dispose();emoteRefresh.Dispose();emoteCache.Dispose();if(chime!=null)chime.Dispose();};RefreshFeed();InitExperience();InitObs();
 }
 Label Label(string text,float size,Color color,bool bold){return new Label{Text=text,UseMnemonic=false,Font=new Font(bold?"Segoe UI Semibold":"Segoe UI",size,FontStyle.Regular),ForeColor=color,Dock=DockStyle.Fill,TextAlign=ContentAlignment.MiddleLeft,AutoEllipsis=true};}
 Button Button(string text,EventHandler action,bool primary=false){var b=new ModernButton{Text=text,AutoSize=true,MinimumSize=new Size(80,38),FlatStyle=FlatStyle.Flat,Primary=primary,BackColor=primary?Theme.Accent:Theme.Raised,ForeColor=primary?Theme.Canvas:Theme.Text,Padding=new Padding(8,3,8,3),Margin=new Padding(0,3,8,3),Cursor=Cursors.Hand};b.FlatAppearance.BorderSize=0;b.Click+=action;return b;}
 async Task ToggleConnection(){if(stop!=null){bridgeButton.Text="Stopping…";stop.Cancel();return;}Uri uri;if(!Uri.TryCreate(endpoint.Text,UriKind.Absolute,out uri)||uri.Scheme!="ws"||!uri.IsLoopback){MessageBox.Show(this,"Use the address for Streamer.bot on this computer. The usual address is ws://127.0.0.1:8080/.","Check the connection address");ShowSettings();return;}stop=new CancellationTokenSource();bridgeButton.Text="Disconnect";endpoint.Enabled=password.Enabled=false;try{await Run(uri,password.Text,stop.Token);}finally{stop.Dispose();stop=null;if(!IsDisposed){bridgeButton.Text="Connect";endpoint.Enabled=password.Enabled=true;}}}

 async Task ToggleTwitch(){if(twitchStop!=null){twitchStop.Cancel();return;}twitchStop=new CancellationTokenSource();var cancellation=twitchStop;connect.Text="Disconnect";twitchTask=RunTwitch(cancellation.Token);try{await twitchTask;}finally{cancellation.Dispose();twitchStop=null;if(twitchLogin!=null&&!twitchLogin.IsDisposed)twitchLogin.Close();twitchLogin=null;if(!IsDisposed){connect.Text="Connect Twitch";if(cancellation.IsCancellationRequested)twitchStatus="Twitch: disconnected";}}}
 async Task RunTwitch(CancellationToken ct){using(var client=new DirectTwitch(
  delegate(string text){if(!IsDisposed)twitchStatus=text;},
  delegate(string code,string url){if(IsDisposed)return;twitchStatus="Twitch: approve sign-in in your browser";twitchLogin=new Form{Text="Connect UniversalStream Assist to Twitch",Size=new Size(560,300),StartPosition=FormStartPosition.CenterParent,BackColor=Theme.Canvas,ForeColor=Theme.Text,Font=Font};var content=new TableLayoutPanel{Dock=DockStyle.Fill,Padding=new Padding(24),RowCount=3};content.RowStyles.Add(new RowStyle(SizeType.Absolute,65));content.RowStyles.Add(new RowStyle(SizeType.Absolute,70));content.RowStyles.Add(new RowStyle(SizeType.Absolute,50));content.Controls.Add(Label("Approve UniversalStream Assist on Twitch to receive your alerts.",12,Theme.Text,true),0,0);content.Controls.Add(Label("Your sign-in code: "+code,18,Theme.Accent,true),0,1);content.Controls.Add(Button("Open Twitch",delegate{System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo(url){UseShellExecute=true});}),0,2);twitchLogin.Controls.Add(content);twitchLogin.FormClosing+=delegate{if(twitchStop!=null&&twitchStatus.Contains("approve sign-in"))twitchStop.Cancel();};twitchLogin.Show(this);System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo(url){UseShellExecute=true});},
  delegate(string id,string name){if(IsDisposed)return;connectedAccounts["Twitch"]=name;twitchStatus="Twitch: signed in as "+name;if(twitchLogin!=null&&!twitchLogin.IsDisposed)twitchLogin.Close();detectedChannel=id;var reload=ReloadSevenTv();},
  delegate(Alert item){if(!IsDisposed)Add(item);},
  delegate(List<Emote> images){if(IsDisposed)return;sevenTv.LearnTwitch(images);foreach(var prior in alerts.Take(200))PrepareMessage(prior);feed.Invalidate();}
 )){await client.Run(ct);}}
 void ShowSettings(){using(var window=new Form{Text="Connection settings",Size=new Size(620,385),MinimumSize=new Size(620,385),StartPosition=FormStartPosition.CenterParent,BackColor=bg,ForeColor=Color.White,Font=Font}){
  var layout=new TableLayoutPanel{Dock=DockStyle.Fill,Padding=new Padding(24),ColumnCount=1,RowCount=6};foreach(int h in new[]{64,30,40,30,42,50})layout.RowStyles.Add(new RowStyle(SizeType.Absolute,h));window.Controls.Add(layout);
  layout.Controls.Add(Label("These details connect to Streamer.bot on this PC.\nThe default address works for most setups.",11,muted,false),0,0);
  layout.Controls.Add(Label("Connection address",10,Color.White,false),0,1);endpoint.Dock=DockStyle.Fill;layout.Controls.Add(endpoint,0,2);
  layout.Controls.Add(Label("Server password (leave blank if you did not set one)",10,Color.White,false),0,3);password.Dock=DockStyle.Fill;layout.Controls.Add(password,0,4);
  var done=Button("Done",delegate{window.Close();},true);layout.Controls.Add(done,0,5);window.AcceptButton=done;window.ShowDialog(this);layout.Controls.Remove(endpoint);layout.Controls.Remove(password);
 }}
 void ShowSetup(){using(var w=new Form{Text="Let's get you connected",Size=new Size(780,630),MinimumSize=new Size(700,580),StartPosition=FormStartPosition.CenterParent,BackColor=bg,ForeColor=Color.White,Font=Font}){
  string[] titles={"Welcome to your new alert feed","Connect Twitch","Add your Streamlabs tips","Add YouTube and Kick (optional)","Allow the app to receive alerts","You're ready to connect"};
  string[] bodies={"This app puts your stream alerts in one window.\n\nFirst, open Streamer.bot on this computer. It connects to your accounts and passes alerts to this app.\n\nYou do not need to create actions, triggers or individual events. We take care of selecting the alerts.\n\nAlready connected your accounts? Skip ahead to step 5.","In Streamer.bot:\n\n1. Open Platforms > Twitch > Accounts.\n2. Click Login for the Broadcaster Account.\n3. Sign in with the Twitch account you stream from.\n4. Complete the permissions screen.\n\nYou do not need a separate bot account for this app.\nSkip this step if you don't use Twitch.","On the Streamlabs website:\n1. Open Settings > API Settings > API Tokens.\n2. Copy Your Socket API Token.\n\nIn Streamer.bot:\n3. Open Integrations > Streamlabs.\n4. Paste the token and click Connect to Streamlabs.\n5. Turn on Auto Connect and Auto Reconnect.\n\nUse Streamlabs, not Streamlabs Desktop. Keep the token private.","YouTube\nOpen Platforms > YouTube and sign into your channel. In Broadcasts, right-click your live stream and choose Monitor.\n\nKick\nSign into Streamer.bot at the bottom-left of its window. Then sign into Platforms > Kick.\n\nAlso sign into the Streamer.bot website and connect the same Kick account under Account Settings > Connections. Kick needs BOTH connections.\n\nSkip any platforms you don't use.","In Streamer.bot:\n\n1. Open Servers / Clients > WebSocket Server.\n2. Set the address to 127.0.0.1 and the port to 8080.\n3. Turn on Auto-Start, then start the server.\n4. If you set a password here, enter it in this app's Connection settings.\n\nThis is a local server password, not your Twitch or Streamlabs password. Leave it blank if you haven't set one.","Click Finish, then Accounts > Connect bridge.\n\nKeep Streamer.bot open. Once connected, new alerts will appear automatically.\n\nTry Try a preview to explore the feed without connecting or spending any money. Samples are clearly marked.\n\nSetup steps are instructions, not a check of your account connections. Check each account in Streamer.bot if alerts are missing."};
  int page=0;var layout=new TableLayoutPanel{Dock=DockStyle.Fill,Padding=new Padding(28),ColumnCount=1,RowCount=4};layout.RowStyles.Add(new RowStyle(SizeType.Absolute,32));layout.RowStyles.Add(new RowStyle(SizeType.Absolute,62));layout.RowStyles.Add(new RowStyle(SizeType.Percent,100));layout.RowStyles.Add(new RowStyle(SizeType.Absolute,52));w.Controls.Add(layout);
  var progress=Label("",10,accent,true);var title=Label("",22,Color.White,true);var body=new RichTextBox{Dock=DockStyle.Fill,ReadOnly=true,BorderStyle=BorderStyle.None,BackColor=bg,ForeColor=Color.White,Font=new Font("Segoe UI",12),TabStop=false};layout.Controls.Add(progress,0,0);layout.Controls.Add(title,0,1);layout.Controls.Add(body,0,2);
  var nav=new FlowLayoutPanel{Dock=DockStyle.Fill};layout.Controls.Add(nav,0,3);var back=Button("Back",delegate{});var next=Button("Next",delegate{},true);nav.Controls.Add(back);nav.Controls.Add(next);nav.Controls.Add(Button("Connection settings",delegate{ShowSettings();}));nav.Controls.Add(Button("Full guide",delegate{ShowGuide();}));
  Action render=delegate{progress.Text="STEP "+(page+1)+" OF "+titles.Length;title.Text=titles[page];body.Text=bodies[page];back.Enabled=page>0;next.Text=page==titles.Length-1?"Finish":"Next";};back.Click+=delegate{if(page>0)page--;render();};next.Click+=delegate{if(page==titles.Length-1){w.Close();return;}page++;render();};render();w.AcceptButton=next;w.ShowDialog(this);
 }}
 void ShowGuide(){using(var guide=new Form{Text="Setup guide",Size=new Size(820,680),StartPosition=FormStartPosition.CenterParent,BackColor=bg}){var text=new RichTextBox{Dock=DockStyle.Fill,ReadOnly=true,BackColor=panel,ForeColor=Color.White,Font=new Font("Segoe UI",11),BorderStyle=BorderStyle.None,DetectUrls=true};try{text.Text=File.ReadAllText(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"START-HERE.txt"));}catch(IOException){text.Text="The guide is missing. Extract the whole ZIP, or use Account setup for step-by-step instructions.";}text.LinkClicked+=delegate(object sender,LinkClickedEventArgs e){Uri link;if(Uri.TryCreate(e.LinkText,UriKind.Absolute,out link)&&link.Scheme=="https")System.Diagnostics.Process.Start(link.AbsoluteUri);};guide.Padding=new Padding(20);guide.Controls.Add(text);guide.ShowDialog(this);}}
 static string Friendly(string kind){switch(kind){case "Follow":return "New follower";case "Sub":case "Subscription":return "New subscriber";case "ReSub":case "Resubscription":return "Resubscribed";case "GiftSub":case "GiftSubscription":return "Gifted subscription";case "GiftBomb":case "MassGiftSubscription":return "Gifted subscriptions";case "Cheer":return "Sent bits";case "NewSponsor":return "New member";case "NewSubscriber":return "New subscriber";case "SuperChat":return "Super Chat";case "SuperSticker":return "Super Sticker";case "MemberMileStone":return "Member milestone";case "MembershipGift":return "Gifted memberships";case "GiftMembershipReceived":return "Received membership";case "Donation":case "Tip":return "Sent a tip";case "KicksGifted":return "Sent Kicks";case "JewelsGifted":return "Sent Jewels";case "CharityDonation":return "Charity donation";default:return kind;}}
 void RefreshFeed(){feed.BeginUpdate();feed.Items.Clear();string query=search.Text.ToLowerInvariant();foreach(var a in alerts){string friendly=Friendly(a.Kind);if(filter.SelectedIndex>0&&!a.Platform.Equals(filter.Text,StringComparison.OrdinalIgnoreCase))continue;if(!(a.Name+" "+a.Kind+" "+friendly+" "+a.Detail).ToLowerInvariant().Contains(query))continue;string time=a.Time.Length>=19?a.Time.Substring(11):a.Time;var row=new ListViewItem(new[]{time,a.Platform,(a.Demo?"Sample · ":"")+friendly,a.Name,a.Detail});row.Tag=a;row.ForeColor=a.Platform.Equals("Twitch",StringComparison.OrdinalIgnoreCase)?Color.FromArgb(202,173,255):a.Platform.Equals("Kick",StringComparison.OrdinalIgnoreCase)?Color.FromArgb(151,231,137):a.Platform.Equals("YouTube",StringComparison.OrdinalIgnoreCase)?Color.FromArgb(255,164,167):accent;feed.Items.Add(row);}feed.EndUpdate();empty.Visible=feed.Items.Count==0;empty.Text=alerts.Count==0?"Your next great moment starts here\n\nOpen Connections to sign in, or try sample alerts.":"No matching alerts\n\nTry another platform or clear your search.";summary.Text=alerts.Count==0?"Activity feed":alerts.Count(a=>!a.Demo)+" alerts   ·   "+alerts.Count(a=>a.Demo)+" samples";totals.Text=feed.Items.Count+" shown · Newest first · Double-click for details\nHistory: "+(preferences.Retention==0?"not saved":preferences.Retention+" days")+" · Latest 2,000 alerts.";}
 void ShowSoundSettings(){using(var w=new Form{Text="Notification sound",Size=new Size(640,350),MinimumSize=new Size(640,350),StartPosition=FormStartPosition.CenterParent,BackColor=Theme.Canvas,ForeColor=Theme.Text,Font=Font}){
 var layout=new TableLayoutPanel{Dock=DockStyle.Fill,Padding=new Padding(24),ColumnCount=1,RowCount=4};layout.RowStyles.Add(new RowStyle(SizeType.Absolute,55));layout.RowStyles.Add(new RowStyle(SizeType.Absolute,76));layout.RowStyles.Add(new RowStyle(SizeType.Absolute,66));layout.RowStyles.Add(new RowStyle(SizeType.Percent,100));w.Controls.Add(layout);
 layout.Controls.Add(Label("Choose your notification sound",20,Theme.Text,true),0,0);var selected=Label("",11,Theme.Muted,false);Action update=delegate{selected.Text="Current: "+(chime==null?"Windows default":Path.GetFileName(chime.SoundLocation))+"\nUse a short WAV file (up to 20 MB). MP3 is not supported.";};update();layout.Controls.Add(selected,0,1);
 var buttons=new FlowLayoutPanel{Dock=DockStyle.Fill};layout.Controls.Add(buttons,0,2);
 Action<string> change=delegate(string path){try{var replacement=SoundPreferences.Load(path);try{SoundPreferences.Save(path);}catch{replacement.Dispose();throw;}if(chime!=null){chime.Stop();chime.Dispose();}chime=replacement;update();}catch(Exception ex){MessageBox.Show(w,"Could not use that sound. "+ex.Message,"Sound not changed");}};
 buttons.Controls.Add(Button("Choose WAV…",delegate{using(var picker=new OpenFileDialog{Title="Choose a notification sound",Filter="WAV audio|*.wav",CheckFileExists=true})if(picker.ShowDialog(w)==DialogResult.OK)change(picker.FileName);},true));buttons.Controls.Add(Button("Play",delegate{try{if(chime!=null)chime.Play();else System.Media.SystemSounds.Asterisk.Play();}catch{MessageBox.Show(w,"That sound file is unavailable. Choose it again.");}}));buttons.Controls.Add(Button("Use default",delegate{change(SoundPreferences.DefaultPath);}));layout.Controls.Add(Button("Done",delegate{w.Close();}),0,3);w.ShowDialog(this);
 }}
 void RestoreWindow(){if(IntegratedHost.Active){IntegratedHost.Emit(new{type="focus"});return;}Show();if(WindowState==FormWindowState.Minimized)WindowState=FormWindowState.Normal;Activate();}
 void NotifyDesktop(Alert alert){if(alert.Runs.Count==0)PrepareMessage(alert);PlayEventSound(alert);if(ShowEventPopup(alert)&&popup!=null)popup.Present(alert,Friendly(alert.Kind),emoteCache,Screen.FromControl(this).WorkingArea); }
 void PrepareMessage(Alert a){a.Runs=InlineMessage.Resolve(a,sevenTv);foreach(string url in a.Runs.Where(r=>r.Url!=null).Select(r=>r.Url).Distinct().Take(128)){var pending=emoteCache.Load(url,delegate{if(!IsDisposed){feed.Invalidate();if(chatList!=null)chatList.Invalidate();if(popup!=null)popup.RefreshEmotes(a,emoteCache);}});}}
 async Task ReloadSevenTv(){await sevenTv.Refresh("twitch",detectedChannel,emoteSetOverride,delegate{if(IsDisposed)return;foreach(var a in alerts.Take(200))PrepareMessage(a);feed.Invalidate();});}
 void ShowSevenTv(){using(var w=new Form{Text="Twitch & 7TV emotes",Size=new Size(760,460),MinimumSize=new Size(760,460),StartPosition=FormStartPosition.CenterParent,BackColor=Theme.Canvas,ForeColor=Theme.Text,Font=Font}){
 var layout=new TableLayoutPanel{Dock=DockStyle.Fill,Padding=new Padding(24),RowCount=5,ColumnCount=1};foreach(int height in new[]{52,130,64,40,66})layout.RowStyles.Add(new RowStyle(SizeType.Absolute,height));w.Controls.Add(layout);layout.Controls.Add(Label("Twitch & 7TV emotes",20,Theme.Text,true),0,0);var state=Label(sevenTv.TwitchStatus+"\n"+sevenTv.Status,11,Theme.Accent,false);layout.Controls.Add(state,0,1);layout.Controls.Add(Label("Your Twitch channel is detected through Streamer.bot.\nOptional: paste a 7TV emote-set link below to use another set this session.",10,Theme.Muted,false),0,2);var entry=new TextBox{Dock=DockStyle.Fill,BackColor=Theme.Raised,ForeColor=Theme.Text,Text=emoteSetOverride};layout.Controls.Add(entry,0,3);var actions=new FlowLayoutPanel{Dock=DockStyle.Fill};layout.Controls.Add(actions,0,4);Button reload=null;reload=Button("Reload emotes",async delegate{try{emoteSetOverride=SevenTvCatalog.SetId(entry.Text);reload.Enabled=false;await ReloadSevenTv();state.Text=sevenTv.TwitchStatus+"\n"+sevenTv.Status;}catch(ArgumentException ex){MessageBox.Show(w,ex.Message);}finally{if(!w.IsDisposed)reload.Enabled=true;}},true);actions.Controls.Add(reload);actions.Controls.Add(Button("Done",delegate{w.Close();}));w.ShowDialog(this);
 }}
 void ShowSelectedAlert(){if(feed.SelectedItems.Count==0)return;var a=(Alert)feed.SelectedItems[0].Tag;using(var w=new Form{Text="Alert details",Size=new Size(720,440),StartPosition=FormStartPosition.CenterParent,BackColor=Theme.Canvas,ForeColor=Theme.Text,Font=Font}){var layout=new TableLayoutPanel{Dock=DockStyle.Fill,Padding=new Padding(24),ColumnCount=1,RowCount=3};layout.RowStyles.Add(new RowStyle(SizeType.Absolute,68));layout.RowStyles.Add(new RowStyle(SizeType.Percent,100));layout.RowStyles.Add(new RowStyle(SizeType.Absolute,44));w.Controls.Add(layout);layout.Controls.Add(Label(a.Name+" — "+Friendly(a.Kind)+"\n"+a.Platform+" · "+a.Time+(a.Demo?" · Sample":""),12,Theme.Text,true),0,0);var scroll=new Panel{Dock=DockStyle.Fill,AutoScroll=true,BackColor=Theme.Surface};var body=new MessageView{Alert=a,Cache=emoteCache,Font=Font,Location=new Point(10,10),Width=620,Height=Math.Min(16000,Math.Max(100,a.Detail.Length*32/35+64))};scroll.Controls.Add(body);scroll.Resize+=delegate{body.Width=Math.Max(100,scroll.ClientSize.Width-36);};layout.Controls.Add(scroll,0,1);var footer=new FlowLayoutPanel{Dock=DockStyle.Fill};footer.Controls.Add(Button("Copy message",delegate{Clipboard.SetText(a.Detail==""?" ":a.Detail);}));footer.Controls.Add(Button("Emote status",delegate{var lines=a.Runs.Where(r=>r.Url!=null).Select(r=>r.Text+": "+emoteCache.Describe(r.Url)).Distinct().ToArray();MessageBox.Show(w,(lines.Length==0?"No matching image data was received for this message.":string.Join("\n",lines))+"\n\n"+sevenTv.TwitchStatus+"\n"+sevenTv.Status,"Emote status");}));layout.Controls.Add(footer,0,2);w.ShowDialog(this);}}
 void Add(Alert a){if(a==null)return;if(a.Kind=="Chat"){AddChat(a);return;}alerts.Insert(0,a);RecordArrival(a);if(!a.Demo&&!previewing)RunTools(Category(a.Kind),new{source="UniversalStream Assist",platform=a.Platform,eventType=a.Kind,viewer=a.Name,message=a.Detail});if(alerts.Count>2000)alerts.RemoveAt(2000);PrepareMessage(a);RefreshFeed();if(!previewing)NotifyDesktop(a);}
 void Samples(){previewing=true;try{alerts.RemoveAll(a=>a.Demo);string[] sources={"Twitch","Twitch","YouTube","Kick","Streamlabs"},types={"Follow","Cheer","SuperChat","Subscription","Donation"};for(int i=0;i<sources.Length;i++)Add(new Alert{Time=DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss"),Platform=sources[i],Kind=types[i],Name=new[]{"LunarFox","PixelPilot","NovaPlays","NightOwl","CozyViewer"}[i],Detail=new[]{"Welcome to the community!","500 bits","5.00 GBP — Great stream!","New subscriber","10.00 GBP — Thank you!"}[i],Demo=true});}finally{previewing=false;}var sample=alerts.FirstOrDefault(a=>a.Demo);if(sample!=null)NotifyDesktop(sample);}
 void Export(){using(var dialog=new SaveFileDialog{Filter="JSON file|*.json",FileName="stream-alerts.json"})if(dialog.ShowDialog(this)==DialogResult.OK)try{File.WriteAllText(dialog.FileName,Protocol.Json.Serialize(alerts),Encoding.UTF8);}catch(Exception){MessageBox.Show(this,"Could not save that file. Please choose another folder.","Could not save alerts");}}

 async Task Send(ClientWebSocket ws,object request,CancellationToken ct) {byte[] bytes=Encoding.UTF8.GetBytes(Protocol.Json.Serialize(request));await ws.SendAsync(new ArraySegment<byte>(bytes),WebSocketMessageType.Text,true,ct);}
 async Task<Dictionary<string,object>> Receive(ClientWebSocket ws,CancellationToken ct) {using(var m=new MemoryStream()){var b=new byte[8192];WebSocketReceiveResult r;do{r=await ws.ReceiveAsync(new ArraySegment<byte>(b),ct);if(r.MessageType==WebSocketMessageType.Close)throw new IOException("Bridge closed");if(r.MessageType!=WebSocketMessageType.Text)throw new IOException("Unexpected message");m.Write(b,0,r.Count);if(m.Length>1048576)throw new IOException("Message too large");}while(!r.EndOfMessage);return Protocol.Json.Deserialize<Dictionary<string,object>>(Encoding.UTF8.GetString(m.ToArray()));}}
 async Task Run(Uri uri,string secret,CancellationToken ct) {
  while(!ct.IsCancellationRequested) {
   try {using(var ws=new ClientWebSocket()) {using(var handshake=CancellationTokenSource.CreateLinkedTokenSource(ct)) {handshake.CancelAfter(15000);status.Text="Connecting to Streamer.bot…";await ws.ConnectAsync(uri,handshake.Token);var hello=await Receive(ws,handshake.Token);if(Protocol.Pick(hello,"request")!="Hello")throw new IOException("Missing greeting");if(Protocol.Get(hello,"authentication")!=null){await Send(ws,new{request="Authenticate",id="auth",authentication=Protocol.Hash(Protocol.Hash(secret+Protocol.Pick(hello,"authentication.salt"))+Protocol.Pick(hello,"authentication.challenge"))},handshake.Token);var auth=await Receive(ws,handshake.Token);if(Protocol.Pick(auth,"status")!="ok"){status.Text="Password rejected. Open Connection settings and enter the password from Streamer.bot > WebSocket Server.";return;}}
    await Send(ws,new{request="GetEvents",id="catalog"},handshake.Token);var catalog=await Receive(ws,handshake.Token);var available=Protocol.Get(catalog,"events") as Dictionary<string,object>;if(available==null)throw new IOException("No event catalog");var selected=new Dictionary<string,List<string>>();foreach(var group in available){var names=group.Value as System.Collections.IEnumerable;if(names==null)continue;foreach(var n in names){if(Protocol.Supported(group.Key,n.ToString())||(group.Key=="Twitch"&&n.ToString()=="ChatMessage")){if(!selected.ContainsKey(group.Key))selected[group.Key]=new List<string>();selected[group.Key].Add(n.ToString());}}}if(selected.Count==0)throw new IOException("No supported events");await Send(ws,new{request="Subscribe",id="subscribe",events=selected},handshake.Token);
    bool accepted=false;while(!accepted){var ack=await Receive(ws,handshake.Token);if(Protocol.Pick(ack,"id")=="subscribe"){if(Protocol.Pick(ack,"status")!="ok")throw new IOException("Subscription rejected");accepted=true;}}await Send(ws,new{request="GetBroadcaster",id="notify-broadcaster"},ct);await Send(ws,new{request="TwitchGetEmotes",id="notify-twitch-emotes"},ct);status.Text="Listening for new alerts. Keep Streamer.bot open. Check your account connections there if an alert is missing.";
   }
   while(!ct.IsCancellationRequested){var message=await Receive(ws,ct);if(Protocol.Pick(message,"id")=="notify-twitch-emotes"){sevenTv.ImportTwitch(message);foreach(var prior in alerts.Take(200))PrepareMessage(prior);continue;}if(Protocol.Pick(message,"id")=="notify-broadcaster"){string broadcasterId=Protocol.Pick(message,"platforms.twitch.broadcastUserId");if(broadcasterId!=""&&broadcasterId!=detectedChannel){detectedChannel=broadcasterId;var refresh=ReloadSevenTv();}continue;}if(Protocol.Pick(message,"event.source")=="Twitch"&&sevenTv.LearnTwitch(Protocol.ReadEmotes(Protocol.Get(message,"data")))){foreach(var prior in alerts.Take(200))PrepareMessage(prior);feed.Invalidate();}var alert=Protocol.Parse(message);if(alert==null||((twitchStop!=null&&alert.Platform=="Twitch")||(streamlabsStop!=null&&alert.Platform=="Streamlabs")||(youtubeStop!=null&&alert.Platform=="YouTube")||(kickStop!=null&&alert.Platform=="Kick")))continue;string id=Protocol.Pick(message,"data.messageId","data.eventId");if(id!=""){string key=alert.Platform+":"+alert.Kind+":"+id;if(!seen.Add(key))continue;seenOrder.Enqueue(key);if(seenOrder.Count>4000)seen.Remove(seenOrder.Dequeue());}Add(alert);}
  }}catch(OperationCanceledException){if(ct.IsCancellationRequested)break;status.Text="Connection timed out. Retrying in 5 seconds…";}catch(Exception){status.Text="Cannot reach Streamer.bot. Open it and start its WebSocket Server (setup step 5). Trying again in 5 seconds…";}
  try{await Task.Delay(5000,ct);}catch(OperationCanceledException){break;}
  }
  status.Text="Disconnected. Click Connect when you are ready. Alerts received while disconnected will not appear here.";
 }
 [STAThread] public static void Main(string[] args) {EmoteNetwork.Configure();Application.EnableVisualStyles();Application.SetCompatibleTextRenderingDefault(false);if(args.Contains("--integrated")||args.Contains("--integration-test")){IntegratedHost.Run(args.Contains("--integration-test"));return;}Application.Run(new MainWindow());}
}

















