using System;using System.Collections.Generic;using System.Drawing;using System.IO;using System.Linq;using System.Net;using System.Net.Sockets;using System.Security.Cryptography;using System.Text;using System.Threading;using System.Threading.Tasks;using System.Windows.Forms;using System.Web.Script.Serialization;
public sealed class ChatAppearance {
 public string font="Arial",text="#f7f0ff",name="#c8a3ff",background="#251937";
 public int size=20,emote=30,limit=30,duration=0;public bool transparent=true,timestamps=true,platforms=true;
 public void Validate(){if(string.IsNullOrEmpty(font)||font.Length>80||!System.Text.RegularExpressions.Regex.IsMatch(font,@"^[\p{L}\p{N} _-]+$"))font="Arial";foreach(var field in new[]{"text","name","background"}){var info=GetType().GetField(field);if(!System.Text.RegularExpressions.Regex.IsMatch((string)info.GetValue(this)??"",@"^#[0-9a-fA-F]{6}$"))info.SetValue(this,field=="background"?"#251937":field=="name"?"#c8a3ff":"#f7f0ff");}size=Math.Max(12,Math.Min(40,size));emote=Math.Max(16,Math.Min(64,emote));limit=Math.Max(1,Math.Min(100,limit));duration=Math.Max(0,Math.Min(600,duration));}
}
public sealed class ObsSettings {public ChatAppearance style=new ChatAppearance();public string token="",sendToken="";public bool enabled;}
public sealed class ObsServer:IDisposable {
 readonly string sendToken;readonly Action<string> command;readonly TcpListener listener;readonly string token,host;readonly SemaphoreSlim slots=new SemaphoreSlim(16);readonly CancellationTokenSource stop=new CancellationTokenSource();
 readonly Dictionary<string,byte[]> assets=new Dictionary<string,byte[]>();string json="{\"messages\":[]}",tag="\"0\"";readonly object gate=new object();
 public ObsServer(int port,string key,Action<string> dispatch=null,string senderKey=null){sendToken=senderKey;command=dispatch;token=key;host="127.0.0.1:"+port;foreach(var name in new[]{"obs.html","obs.js","obs.css"})using(var source=typeof(ObsServer).Assembly.GetManifestResourceStream(name)){if(source==null)throw new IOException("OBS files are missing. Reinstall the app.");using(var data=new MemoryStream()){source.CopyTo(data);assets[name]=data.ToArray();}}listener=new TcpListener(IPAddress.Loopback,port);listener.Start(16);var task=Accept();}
 public void Publish(string value){lock(gate){if(value==json)return;json=value;using(var hash=SHA256.Create())tag="\""+Convert.ToBase64String(hash.ComputeHash(Encoding.UTF8.GetBytes(value)))+"\"";}}
 async Task Accept(){while(!stop.IsCancellationRequested){try{var client=await listener.AcceptTcpClientAsync();if(!slots.Wait(0)){client.Close();continue;}var task=Serve(client);}catch(ObjectDisposedException){break;}catch(SocketException){if(stop.IsCancellationRequested)break;}}}
 async Task Serve(TcpClient client){try{using(client)using(var stream=client.GetStream())using(var timeout=CancellationTokenSource.CreateLinkedTokenSource(stop.Token)){timeout.CancelAfter(55000);using(timeout.Token.Register(()=>client.Close())){var raw=new StringBuilder();var b=new byte[1];while(raw.Length<8192&&!raw.ToString().EndsWith("\r\n\r\n")){if(await stream.ReadAsync(b,0,1,timeout.Token)==0)return;raw.Append((char)b[0]);}if(!raw.ToString().EndsWith("\r\n\r\n"))return;var lines=raw.ToString().Split(new[]{"\r\n"},StringSplitOptions.None);var request=lines[0].Split(' ');var headers=new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase);foreach(string line in lines.Skip(1)){int index=line.IndexOf(':');if(index>0){string name=line.Substring(0,index);if(headers.ContainsKey(name))return;headers[name]=line.Substring(index+1).Trim();}}string value;int code=200;string type="text/plain",etag="";byte[] body=Encoding.UTF8.GetBytes("Not found");
 if(request.Length!=3||(request[0]!="GET"&&!(request[0]=="POST"&&((command!=null&&request[1]=="/command")||(sendToken!=null&&request[1]=="/chat-send")))))code=405;
 else if(!headers.TryGetValue("Host",out value)||value!=host||(headers.TryGetValue("Origin",out value)&&value!="http://"+host))code=403;
 else if(request[1]=="/command"&&command!=null&&request[0]=="POST"){int length;if(!headers.TryGetValue("Authorization",out value)||value!="Bearer "+token)code=401;else if(headers.ContainsKey("Transfer-Encoding")||!headers.TryGetValue("Content-Length",out value)||!int.TryParse(value,out length)||length<1||length>64)code=400;else{var payload=new byte[length];int offset=0;while(offset<length){int count=await stream.ReadAsync(payload,offset,length-offset,timeout.Token);if(count==0)return;offset+=count;}var name=Encoding.UTF8.GetString(payload);if(!new[]{"toggleSound","pauseRules","resumeRules","replay","showChat"}.Contains(name))code=400;else{command(name);body=Encoding.UTF8.GetBytes("Accepted");code=202;}}}
 else if(request[1]=="/chat-send"&&request[0]=="POST"&&sendToken!=null){int length;if(!headers.TryGetValue("Authorization",out value)||value!="Bearer "+sendToken)code=401;else if(headers.ContainsKey("Transfer-Encoding")||!headers.TryGetValue("Content-Length",out value)||!int.TryParse(value,out length)||length<1||length>4096)code=400;else{var payload=new byte[length];int offset=0;while(offset<length){int count=await stream.ReadAsync(payload,offset,length-offset,timeout.Token);if(count==0)return;offset+=count;}body=Encoding.UTF8.GetBytes(await ChatSend.Send(Encoding.UTF8.GetString(payload)));type="application/json";}}
 else if(request[1]=="/state"){if(!headers.TryGetValue("Authorization",out value)||value!="Bearer "+token)code=401;else{lock(gate){etag=tag;body=Encoding.UTF8.GetBytes(json);}type="application/json";if(headers.TryGetValue("If-None-Match",out value)&&value==etag){code=304;body=new byte[0];}}}
 else if(request[1]=="/dock"||request[1]=="/overlay"||request[1]=="/effects"){body=assets["obs.html"];type="text/html";}
 else if(request[1]=="/obs.js"){body=assets["obs.js"];type="text/javascript";}
 else if(request[1]=="/obs.css"){body=assets["obs.css"];type="text/css";}
 else code=404;
 if(code>=400)body=Encoding.UTF8.GetBytes("Unavailable");string csp="default-src 'none'; script-src 'self'; style-src 'self' 'unsafe-inline'; connect-src 'self'; img-src https://cdn.7tv.app https://static-cdn.jtvnw.net https://files.kick.com https://cdn.betterttv.net https://cdn.frankerfacez.com https://d3aqoihi2n8ty8.cloudfront.net; base-uri 'none'; frame-ancestors file:";
 string response="HTTP/1.1 "+code+" "+(code==202?"Accepted":code==200?"OK":code==304?"Not Modified":"Error")+"\r\nContent-Type: "+type+"; charset=utf-8\r\nContent-Length: "+body.Length+"\r\nConnection: close\r\nCache-Control: no-store\r\nReferrer-Policy: no-referrer\r\nX-Content-Type-Options: nosniff\r\nContent-Security-Policy: "+csp+"\r\n"+(etag==""?"":"ETag: "+etag+"\r\n")+"\r\n";byte[] head=Encoding.UTF8.GetBytes(response);await stream.WriteAsync(head,0,head.Length,timeout.Token);await stream.WriteAsync(body,0,body.Length,timeout.Token);}}}
 catch(Exception){}finally{slots.Release();}}
 public void Dispose(){stop.Cancel();listener.Stop();}
}
public partial class MainWindow {
 static int ObsPort {get{return IntegratedHost.Testing?28741:18741;}}ObsSettings obs=new ObsSettings();ObsServer obsServer;System.Windows.Forms.Timer obsTimer;Font chatFont;string obsError="";
 void InitObs(){InitPulse();try{obs=AccountStore.Read<ObsSettings>("obs-view")??new ObsSettings();}catch{obsError="Saved OBS preferences could not be unlocked.";}if(obs.style==null)obs.style=new ChatAppearance();obs.style.Validate();ApplyChatAppearance();obsTimer=new System.Windows.Forms.Timer{Interval=750};obsTimer.Tick+=delegate{PublishObs();};obsTimer.Start();Shown+=delegate{if(obs.enabled)try{StartObs();}catch(Exception e){obsError=e.Message;}};FormClosed+=delegate{obsTimer.Dispose();if(obsServer!=null)obsServer.Dispose();if(chatFont!=null)chatFont.Dispose();};}
 void SaveObs(){if(!IntegratedHost.Testing)AccountStore.Save("obs-view",obs);}
 void StartObs(){if(obsServer!=null)return;if(obsError!="")throw new IOException(obsError);if(!System.Text.RegularExpressions.Regex.IsMatch(obs.token??"","^[a-f0-9]{64}$")){var bytes=new byte[32];using(var rng=RandomNumberGenerator.Create())rng.GetBytes(bytes);obs.token=BitConverter.ToString(bytes).Replace("-","").ToLowerInvariant();}if(!System.Text.RegularExpressions.Regex.IsMatch(obs.sendToken??"","^[a-f0-9]{64}$")){var sendBytes=new byte[32];using(var rng=RandomNumberGenerator.Create())rng.GetBytes(sendBytes);obs.sendToken=BitConverter.ToString(sendBytes).Replace("-","").ToLowerInvariant();}obs.enabled=true;SaveObs();try{obsServer=new ObsServer(ObsPort,obs.token,null,obs.sendToken);PublishObs();}catch(SocketException){throw new IOException("The OBS port is busy. Close another copy of this app and try again.");}}
 void PublishObs(){PublishControls();if(obsServer==null)return;var messages=chatMessages.Skip(Math.Max(0,chatMessages.Count-100)).Select(a=>new{id=a.ChatId,name=a.Name,platform=a.Platform,received=a.ChatReceived,runs=a.Runs.Take(256).Select(r=>new{text=r.Text,url=r.Url}).ToArray()}).ToArray();obsServer.Publish(new JavaScriptSerializer{MaxJsonLength=8388608}.Serialize(new{style=obs.style,messages=messages,pulse=pulseEffect}));}
 int ChatHeaderHeight{get{return Math.Max(32,(chatFont??Font).Height+12);}}
 void ApplyChatAppearance(){obs.style.Validate();var old=chatFont;chatFont=new Font(obs.style.font,obs.style.size*72f/96f,FontStyle.Regular);if(chatList!=null){chatList.Font=chatFont;chatList.BackColor=ColorTranslator.FromHtml(obs.style.background);chatList.ForeColor=ColorTranslator.FromHtml(obs.style.text);RefreshChat();}if(old!=null)old.Dispose();PublishObs();}
 void ShowChatAppearance(){using(var w=new Form{Text="Chat appearance",Size=new Size(520,650),StartPosition=FormStartPosition.CenterParent,BackColor=Theme.Canvas,ForeColor=Theme.Text,Font=Font}){
 var grid=new TableLayoutPanel{Dock=DockStyle.Fill,Padding=new Padding(22),ColumnCount=2,AutoScroll=true};grid.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,46));grid.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,54));w.Controls.Add(grid);int row=0;Action<string,Control> add=(name,control)=>{grid.RowStyles.Add(new RowStyle(SizeType.Absolute,46));grid.Controls.Add(Label(name,10,Theme.Text,false),0,row);control.Dock=DockStyle.Fill;grid.Controls.Add(control,1,row++);};
 var font=new ComboBox{DropDownStyle=ComboBoxStyle.DropDownList};font.Items.AddRange(FontFamily.Families.Select(x=>x.Name).OrderBy(x=>x).Cast<object>().ToArray());font.SelectedItem=obs.style.font;if(font.SelectedIndex<0)font.SelectedIndex=0;add("Font",font);
 var size=new NumericUpDown{Minimum=12,Maximum=40,Value=obs.style.size};add("Text size",size);var emote=new NumericUpDown{Minimum=16,Maximum=64,Value=obs.style.emote};add("Emote size",emote);
 var colors=new Dictionary<string,Button>();foreach(string key in new[]{"text","name","background"}){string initial=(string)typeof(ChatAppearance).GetField(key).GetValue(obs.style);var b=Button(initial,delegate{});b.Tag=initial;b.Click+=delegate{using(var picker=new ColorDialog{Color=ColorTranslator.FromHtml((string)b.Tag)})if(picker.ShowDialog(w)==DialogResult.OK){b.Tag=ColorTranslator.ToHtml(picker.Color);if(((string)b.Tag)[0]!='#')b.Tag=String.Format("#{0:X2}{1:X2}{2:X2}",picker.Color.R,picker.Color.G,picker.Color.B);b.Text=(string)b.Tag;}};colors[key]=b;add(key=="name"?"Sender colour":key=="text"?"Text colour":"Background colour",b);}
 var transparent=new CheckBox{Checked=obs.style.transparent};add("Transparent OBS overlay",transparent);var stamps=new CheckBox{Checked=obs.style.timestamps};add("Show times",stamps);var platforms=new CheckBox{Checked=obs.style.platforms};add("Show platforms",platforms);var limit=new NumericUpDown{Minimum=1,Maximum=100,Value=obs.style.limit};add("Overlay message limit",limit);var duration=new NumericUpDown{Minimum=0,Maximum=600,Value=obs.style.duration};add("Hide after seconds (0 = keep)",duration);
 add("",Button("Apply",delegate{obs.style.font=(string)font.SelectedItem;obs.style.size=(int)size.Value;obs.style.emote=(int)emote.Value;obs.style.text=(string)colors["text"].Tag;obs.style.name=(string)colors["name"].Tag;obs.style.background=(string)colors["background"].Tag;obs.style.transparent=transparent.Checked;obs.style.timestamps=stamps.Checked;obs.style.platforms=platforms.Checked;obs.style.limit=(int)limit.Value;obs.style.duration=(int)duration.Value;ApplyChatAppearance();try{SaveObs();w.Close();}catch{MessageBox.Show(w,"Could not save preferences. Unlock your Windows profile and try again.");}}));w.ShowDialog(this);}}
 void ShowObs(){try{StartObs();}catch(Exception e){MessageBox.Show(this,e.Message,"OBS connection");return;}using(var w=new Form{Text="Connect chat to OBS",Size=new Size(720,480),StartPosition=FormStartPosition.CenterParent,BackColor=Theme.Canvas,ForeColor=Theme.Text,Font=Font}){var grid=new FlowLayoutPanel{Dock=DockStyle.Fill,FlowDirection=FlowDirection.TopDown,WrapContents=false,Padding=new Padding(24),AutoScroll=true};w.Controls.Add(grid);grid.Controls.Add(new Label{Text="Keep this app open on the same computer as OBS.\nDock: OBS > Docks > Custom Browser Docks.\nOverlay: Sources > + > Browser. Paste the matching link.",Size=new Size(650,85),ForeColor=Theme.Text});Action<string,string> link=(name,path)=>{grid.Controls.Add(new Label{Text=name,AutoSize=true});var text=new TextBox{ReadOnly=true,Width=640,Text="http://127.0.0.1:"+ObsPort+path+"#"+obs.token};grid.Controls.Add(text);grid.Controls.Add(Button("Copy "+name,delegate{Clipboard.SetText(text.Text);}));};link("dock link","/dock");grid.Controls.Add(Button("Copy UniversalCollab chat + send link",delegate{Clipboard.SetText("http://127.0.0.1:"+ObsPort+"/dock#"+obs.token+"."+obs.sendToken);}));link("overlay link","/overlay");grid.Controls.Add(Button("Stop OBS connection",delegate{obs.enabled=false;obsServer.Dispose();obsServer=null;try{SaveObs();}catch{}w.Close();}));grid.Controls.Add(Button("Reset links",delegate{obsServer.Dispose();obsServer=null;obs.token="";obs.sendToken="";try{StartObs();w.Close();MessageBox.Show(this,"Links changed. Open OBS setup again to copy the new links.");}catch(Exception e){MessageBox.Show(w,e.Message);}}));w.ShowDialog(this);}}
}
