using System;using System.Collections.Generic;using System.Linq;using System.IO;using System.Text;using System.Net.WebSockets;using System.Security.Cryptography;using System.Threading;using System.Threading.Tasks;using System.Windows.Forms;using System.Drawing;using System.Web.Script.Serialization;
public sealed class PulseRule {
 public bool Enabled{get;set;} public string Name{get;set;} public string Direction{get;set;} public int Threshold{get;set;} public int Reset{get;set;} public int Hold{get;set;} public int Cooldown{get;set;} public bool Sound{get;set;} public bool Animation{get;set;} public string Scene{get;set;} public string SoundFile{get;set;}
 public PulseRule(){Enabled=true;Name="Heart rate high";Direction="Above";Threshold=120;Reset=110;Hold=5;Cooldown=60;Sound=true;Animation=true;Scene="";SoundFile="";}
 public void Validate(){if(String.IsNullOrWhiteSpace(Name)||Name.Length>100)throw new ArgumentException("Give each rule a name of 1–100 characters.");if(Direction!="Above"&&Direction!="Below")throw new ArgumentException("Direction must be Above or Below.");if(Threshold<30||Threshold>240||Reset<30||Reset>240||(Direction=="Above"?Reset>=Threshold:Reset<=Threshold))throw new ArgumentException("Use 30–240 BPM. Reset must be lower for Above rules, higher for Below rules.");if(Hold<0||Hold>120||Cooldown<5||Cooldown>3600)throw new ArgumentException("Hold: 0–120 seconds. Cooldown: 5–3600 seconds.");if((Scene??"").Length>200)throw new ArgumentException("Scene name is too long.");}
}
public sealed class PulseSettings {public string Token="",Password="";public int Port=4455;public List<PulseRule> Rules=new List<PulseRule>{new PulseRule()};}
public sealed class PulseEngine {
 sealed class State{public bool Armed;public long Since=-1,Last=-3600000;}
 readonly Dictionary<PulseRule,State> states=new Dictionary<PulseRule,State>();long measured=-1,received=-1;
 public void Reset(){foreach(var s in states.Values){s.Armed=false;s.Since=-1;}measured=-1;received=-1;}
 public List<PulseRule> Feed(List<PulseRule> rules,int bpm,long stamp,long now){var fired=new List<PulseRule>();if(bpm<30||bpm>240||stamp<=measured||now-stamp>30000||stamp-now>10000)return fired;if(received>=0&&now-received>15000)Reset();measured=stamp;received=now;foreach(var r in rules){if(!r.Enabled)continue;State s;if(!states.TryGetValue(r,out s)){s=new State();states[r]=s;}bool safe=r.Direction=="Above"?bpm<=r.Reset:bpm>=r.Reset;bool hit=r.Direction=="Above"?bpm>=r.Threshold:bpm<=r.Threshold;if(safe){s.Armed=true;s.Since=-1;}if(!hit){s.Since=-1;continue;}if(!s.Armed)continue;if(s.Since<0)s.Since=now;if(now-s.Since>=r.Hold*1000L&&now-s.Last>=r.Cooldown*1000L){s.Last=now;s.Since=-1;s.Armed=false;fired.Add(r);}}return fired;}
}
public static class PulseWire {
 public static async Task<object> Read(ClientWebSocket ws,CancellationToken ct){using(var m=new MemoryStream()){var b=new byte[4096];WebSocketReceiveResult f;do{f=await ws.ReceiveAsync(new ArraySegment<byte>(b),ct);if(f.MessageType!=WebSocketMessageType.Text)throw new IOException("Connection closed");m.Write(b,0,f.Count);if(m.Length>65536)throw new IOException("Message too large");}while(!f.EndOfMessage);return new JavaScriptSerializer().DeserializeObject(Encoding.UTF8.GetString(m.ToArray()));}}
 public static Task Send(ClientWebSocket ws,object value,CancellationToken ct){return ws.SendAsync(new ArraySegment<byte>(Encoding.UTF8.GetBytes(new JavaScriptSerializer().Serialize(value))),WebSocketMessageType.Text,true,ct);}
 static string Hash(string s){using(var hash=SHA256.Create())return Convert.ToBase64String(hash.ComputeHash(Encoding.UTF8.GetBytes(s)));}
 public static string Auth(string password,string salt,string challenge){return Hash(Hash(password+salt)+challenge);}
 public static async Task Scene(int port,string password,string scene,CancellationToken ct){using(var ws=new ClientWebSocket())using(var deadline=CancellationTokenSource.CreateLinkedTokenSource(ct)){deadline.CancelAfter(8000);var token=deadline.Token;await ws.ConnectAsync(new Uri("ws://127.0.0.1:"+port),token);var hello=await Read(ws,token);if(Protocol.Pick(hello,"op")!="0")throw new IOException("OBS did not send a welcome.");var identify=new Dictionary<string,object>{{"rpcVersion",1},{"eventSubscriptions",0}};if(Protocol.Get(hello,"d.authentication")!=null)identify["authentication"]=Auth(password,Protocol.Pick(hello,"d.authentication.salt"),Protocol.Pick(hello,"d.authentication.challenge"));await Send(ws,new{op=1,d=identify},token);if(Protocol.Pick(await Read(ws,token),"op")!="2")throw new IOException("OBS sign-in failed.");string id=Guid.NewGuid().ToString("N");await Send(ws,new{op=6,d=new{requestType=scene==null?"GetSceneList":"SetCurrentProgramScene",requestId=id,requestData=scene==null?(object)new{}:new{sceneName=scene}}},token);while(true){var response=await Read(ws,token);if(Protocol.Pick(response,"op")=="7"&&Protocol.Pick(response,"d.requestId")==id){if(!Protocol.Pick(response,"d.requestStatus.result").Equals("True",StringComparison.OrdinalIgnoreCase))throw new IOException("OBS rejected the scene. Check its exact name.");return;}}}}
}
public partial class MainWindow {
 PulseSettings pulse=new PulseSettings();PulseEngine pulseEngine=new PulseEngine();CancellationTokenSource pulseStop;string pulseStatus="Stopped",pulseAction="";object pulseEffect=null;long pulseLast=0;System.Windows.Forms.Timer pulseUi;System.Media.SoundPlayer pulsePlayer;bool pulseSceneBusy;
 static long PulseNow(){return DateTimeOffset.UtcNow.ToUnixTimeMilliseconds();}
 void InitPulse(){InitTools();pulse=AccountStore.Read<PulseSettings>("pulsoid")??new PulseSettings();try{if(pulse.Port<1024||pulse.Port>65535)throw new Exception();if(pulse.Rules==null||pulse.Rules.Count>20)throw new Exception();foreach(var r in pulse.Rules)r.Validate();}catch{pulse=new PulseSettings();}FormClosed+=delegate{StopPulse();if(pulsePlayer!=null)pulsePlayer.Dispose();};}
 void StopPulse(){if(pulseStop!=null){pulseStop.Cancel();pulseStop=null;}pulseEngine.Reset();pulseLast=0;pulseEffect=null;pulseStatus="Stopped";}
 async void StartPulse(){StopPulse();if(String.IsNullOrWhiteSpace(pulse.Token)){pulseStatus="Add your Pulsoid token first.";return;}var source=new CancellationTokenSource();pulseStop=source;var ct=source.Token;int failures=0;while(!ct.IsCancellationRequested){try{pulseStatus="Connecting to Pulsoid…";using(var ws=new ClientWebSocket()){ws.Options.SetRequestHeader("Authorization","Bearer "+pulse.Token);using(var timeout=CancellationTokenSource.CreateLinkedTokenSource(ct)){timeout.CancelAfter(15000);await ws.ConnectAsync(new Uri("wss://dev.pulsoid.net/api/v1/data/real_time"),timeout.Token);}failures=0;pulseStatus="Connected · Waiting for a fresh reading";while(!ct.IsCancellationRequested){object data;using(var timeout=CancellationTokenSource.CreateLinkedTokenSource(ct)){timeout.CancelAfter(20000);data=await PulseWire.Read(ws,timeout.Token);}int bpm;long stamp;long now=PulseNow();if(!int.TryParse(Protocol.Pick(data,"data.heart_rate"),out bpm)||!long.TryParse(Protocol.Pick(data,"measured_at"),out stamp)||bpm<30||bpm>240||now-stamp>30000||stamp-now>10000)continue;pulseLast=now;pulseStatus=bpm+" BPM · Rules listening";var fired=pulseEngine.Feed(pulse.Rules,bpm,stamp,now);bool sceneUsed=false;foreach(var r in fired){FirePulse(r,bpm,!sceneUsed);if(!String.IsNullOrWhiteSpace(r.Scene))sceneUsed=true;}}}}catch{if(ct.IsCancellationRequested)break;pulseEngine.Reset();pulseLast=0;pulseStatus="Pulsoid unavailable · Check token/monitor. Retrying…";}try{await Task.Delay(Math.Min(60000,2000*(1<<Math.Min(failures++,5))),ct);}catch{break;}}source.Dispose();}
 async void FirePulse(PulseRule r,int bpm,bool allowScene,bool automation=true){pulseAction=r.Name+" · "+bpm+" BPM";if(automation)RunTools("Pulsoid: "+r.Name,new{source="UniversalStream Assist",heartRate=bpm,rule=r.Name});if(r.Animation)pulseEffect=new{id=Guid.NewGuid().ToString("N"),text=r.Name,bpm=bpm,until=PulseNow()+8000};if(r.Sound)try{if(pulsePlayer!=null)pulsePlayer.Dispose();pulsePlayer=SoundPreferences.Load(String.IsNullOrWhiteSpace(r.SoundFile)?SoundPreferences.DefaultPath:r.SoundFile);pulsePlayer.Play();}catch{pulseAction+=" · Sound unavailable";}PublishObs();if(allowScene&&!String.IsNullOrWhiteSpace(r.Scene)){if(pulseSceneBusy){pulseAction+=" · Scene busy (skipped)";return;}pulseSceneBusy=true;try{await PulseWire.Scene(pulse.Port,pulse.Password,r.Scene,pulseStop==null?CancellationToken.None:pulseStop.Token);pulseAction+=" · Scene changed";}catch{pulseAction+=" · Scene failed: check OBS WebSocket/password and scene name";}finally{pulseSceneBusy=false;}}}
 void ShowPulse(){using(var w=new Form{Text="Pulsoid · Heart-rate actions",Size=new Size(1100,720),MinimumSize=new Size(850,600),StartPosition=FormStartPosition.CenterParent,BackColor=Theme.Canvas,ForeColor=Theme.Text,Font=Font}){var layout=new TableLayoutPanel{Dock=DockStyle.Fill,Padding=new Padding(18),ColumnCount=1,RowCount=5};layout.RowStyles.Add(new RowStyle(SizeType.Absolute,135));layout.RowStyles.Add(new RowStyle(SizeType.Absolute,70));layout.RowStyles.Add(new RowStyle(SizeType.Percent,100));layout.RowStyles.Add(new RowStyle(SizeType.Absolute,100));layout.RowStyles.Add(new RowStyle(SizeType.Absolute,60));w.Controls.Add(layout);
 var top=new FlowLayoutPanel{Dock=DockStyle.Fill};var token=new TextBox{Width=280,UseSystemPasswordChar=true,Text=pulse.Token};var password=new TextBox{Width=220,UseSystemPasswordChar=true,Text=pulse.Password};var port=new NumericUpDown{Minimum=1024,Maximum=65535,Value=pulse.Port,Width=90};top.Controls.Add(new Label{Text="Pulsoid API token",AutoSize=true});top.Controls.Add(token);top.Controls.Add(new Label{Text="OBS password",AutoSize=true});top.Controls.Add(password);top.Controls.Add(new Label{Text="OBS port",AutoSize=true});top.Controls.Add(port);var info=new Label{Text="Create a personal Pulsoid token with data:heart_rate:read.\nOBS: Tools > WebSocket Server Settings > Enable (same computer).\nRules start stopped. A fresh reading must reach the reset side before a rule can fire.",AutoSize=true,MaximumSize=new Size(990,0)};top.SetFlowBreak(port,true);top.Controls.Add(info);layout.Controls.Add(top,0,0);
 var statusLabel=new Label{Dock=DockStyle.Fill};layout.Controls.Add(statusLabel,0,1);
 var rows=new System.ComponentModel.BindingList<PulseRule>(new JavaScriptSerializer().Deserialize<List<PulseRule>>(new JavaScriptSerializer().Serialize(pulse.Rules)));var grid=new DataGridView{Dock=DockStyle.Fill,DataSource=rows,AutoGenerateColumns=true,BackgroundColor=Theme.Surface,ForeColor=Color.Black,AllowUserToAddRows=false,AutoSizeColumnsMode=DataGridViewAutoSizeColumnsMode.AllCells};grid.DataError+=delegate(object sender,DataGridViewDataErrorEventArgs e){e.ThrowException=false;};layout.Controls.Add(grid,0,2);
 var controls=new FlowLayoutPanel{Dock=DockStyle.Fill};controls.Controls.Add(Button("Add rule",delegate{if(rows.Count<20)rows.Add(new PulseRule());}));controls.Controls.Add(Button("Remove selected",delegate{if(grid.CurrentRow!=null)rows.Remove((PulseRule)grid.CurrentRow.DataBoundItem);}));controls.Controls.Add(Button("Choose WAV",delegate{if(grid.CurrentRow==null)return;using(var picker=new OpenFileDialog{Filter="WAV audio|*.wav"})if(picker.ShowDialog(w)==DialogResult.OK)try{using(var sound=SoundPreferences.Load(picker.FileName)){}((PulseRule)grid.CurrentRow.DataBoundItem).SoundFile=picker.FileName;grid.Refresh();}catch(Exception e){MessageBox.Show(w,e.Message);}}));controls.Controls.Add(Button("Preview sound + animation",delegate{if(grid.CurrentRow==null)return;var r=(PulseRule)grid.CurrentRow.DataBoundItem;FirePulse(new PulseRule{Name="Preview · "+r.Name,Sound=r.Sound,Animation=r.Animation,SoundFile=r.SoundFile},120,false,false);}));controls.Controls.Add(Button("Copy effects overlay",delegate{try{StartObs();Clipboard.SetText("http://127.0.0.1:"+ObsPort+"/effects#"+obs.token);}catch(Exception e){MessageBox.Show(w,e.Message);}}));controls.Controls.Add(Button("Test OBS connection",async delegate{try{await PulseWire.Scene((int)port.Value,password.Text,null,CancellationToken.None);MessageBox.Show(w,"OBS connection works. No scene was changed.");}catch{MessageBox.Show(w,"Could not connect. Check OBS WebSocket is enabled, its port and password.");}}));layout.Controls.Add(controls,0,3);
 var bottom=new FlowLayoutPanel{Dock=DockStyle.Fill};bottom.Controls.Add(Button("Save & start rules",delegate{try{grid.EndEdit();w.BindingContext[rows].EndCurrentEdit();foreach(var r in rows)r.Validate();if(token.Text.Trim().Length<16||token.Text.Length>4096)throw new ArgumentException("Enter a valid Pulsoid API token.");var next=new PulseSettings{Token=token.Text.Trim(),Password=password.Text,Port=(int)port.Value,Rules=rows.ToList()};AccountStore.Save("pulsoid",next);StopPulse();pulse=next;pulseEngine=new PulseEngine();StartPulse();}catch(Exception e){MessageBox.Show(w,e.Message);}}));bottom.Controls.Add(Button("Stop rules",delegate{StopPulse();}));bottom.Controls.Add(Button("Forget credentials",delegate{StopPulse();AccountStore.Forget("pulsoid");pulse.Token=pulse.Password="";token.Text=password.Text="";}));layout.Controls.Add(bottom,0,4);
 using(pulseUi=new System.Windows.Forms.Timer{Interval=500}){pulseUi.Tick+=delegate{statusLabel.Text=(pulseLast>0&&PulseNow()-pulseLast>15000?"No fresh readings · Rules paused":pulseStatus)+"\n"+pulseAction;};pulseUi.Start();w.ShowDialog(this);}}}
}
