using System;using System.Collections.Generic;using System.Linq;using System.Drawing;using System.Windows.Forms;using System.Net.WebSockets;using System.Net.Http;using System.Text;using System.Threading;using System.Threading.Tasks;using System.IO;
public sealed class ToolMapping {public string Trigger="",ActionId="",Lumia="";}
public sealed class ToolSettings {public bool StreamerBot,LumiaEnabled;public string ControlToken="";public int Port=8080;public string Password="",LumiaToken="";public List<ToolMapping> Mappings=new List<ToolMapping>();}
public sealed class ToolAction {public string Id,Name;public override string ToString(){return Name;}}
public static class ToolWire {
 public static async Task<object> Bot(int port,string password,string action,object args,CancellationToken token){if(port<1024||port>65535)throw new ArgumentException("Use a port between 1024 and 65535.");using(var stop=CancellationTokenSource.CreateLinkedTokenSource(token))using(var ws=new ClientWebSocket()){stop.CancelAfter(8000);var ct=stop.Token;await ws.ConnectAsync(new Uri("ws://127.0.0.1:"+port+"/"),ct);var hello=await PulseWire.Read(ws,ct);if(Protocol.Pick(hello,"request")!="Hello")throw new IOException("Streamer.bot greeting missing.");if(Protocol.Get(hello,"authentication")!=null){await PulseWire.Send(ws,new{request="Authenticate",id="auth",authentication=PulseWire.Auth(password,Protocol.Pick(hello,"authentication.salt"),Protocol.Pick(hello,"authentication.challenge"))},ct);var auth=await PulseWire.Read(ws,ct);if(Protocol.Pick(auth,"status")!="ok")throw new IOException("Streamer.bot password rejected.");}string id=Guid.NewGuid().ToString("N");await PulseWire.Send(ws,action==null?(object)new{request="GetActions",id=id}:new{request="DoAction",id=id,action=new{id=action},args=args},ct);while(true){var data=await PulseWire.Read(ws,ct);if(Protocol.Pick(data,"id")!=id)continue;if(Protocol.Pick(data,"status")!="ok")throw new IOException("Streamer.bot rejected the request.");return data;}}}
 public static async Task Lumia(string token,string command,CancellationToken ct){if(String.IsNullOrWhiteSpace(token)||String.IsNullOrWhiteSpace(command))throw new ArgumentException("Set the Lumia token and command first.");using(var http=new HttpClient(new HttpClientHandler{AllowAutoRedirect=false,UseCookies=false}){Timeout=TimeSpan.FromSeconds(5),MaxResponseContentBufferSize=65536})using(var body=new StringContent(Protocol.Json.Serialize(new{type="chat-command",@params=new{value=command}}),Encoding.UTF8,"application/json"))using(var response=await http.PostAsync("http://127.0.0.1:39231/api/send?token="+Uri.EscapeDataString(token),body,ct)){if(!response.IsSuccessStatusCode)throw new IOException("Lumia rejected the command. Check its name and API token.");var data=Protocol.Json.DeserializeObject(await response.Content.ReadAsStringAsync());int code;if(int.TryParse(Protocol.Pick(data,"status"),out code)&&code>=400)throw new IOException("Lumia rejected the command.");}}
}
public partial class MainWindow {
 ToolSettings toolsConfig=new ToolSettings();string toolsStatus="Not configured";readonly Dictionary<string,DateTime> toolLast=new Dictionary<string,DateTime>();int toolActive;readonly CancellationTokenSource toolStop=new CancellationTokenSource();
 void InitTools(){InitCollab();try{toolsConfig=AccountStore.Read<ToolSettings>("integrations")??new ToolSettings();}catch{toolsStatus="Saved integration settings could not be unlocked.";}if(toolsConfig.Mappings==null)toolsConfig.Mappings=new List<ToolMapping>();FormClosed+=delegate{toolStop.Cancel();if(controlServer!=null)controlServer.Dispose();};}
 async void RunTools(string trigger,object args){var mapping=toolsConfig.Mappings.FirstOrDefault(x=>x.Trigger==trigger);if(mapping==null)return;DateTime last;if(toolActive>=2||(toolLast.TryGetValue(trigger,out last)&&(DateTime.UtcNow-last).TotalSeconds<5))return;toolLast[trigger]=DateTime.UtcNow;toolActive++;try{if(toolsConfig.StreamerBot&&!String.IsNullOrEmpty(mapping.ActionId)){try{await ToolWire.Bot(toolsConfig.Port,toolsConfig.Password,mapping.ActionId,args,toolStop.Token);toolsStatus="Streamer.bot action sent";}catch{toolsStatus="Streamer.bot action failed. Check server/password/action.";}}if(toolsConfig.LumiaEnabled&&!String.IsNullOrWhiteSpace(mapping.Lumia)){try{await ToolWire.Lumia(toolsConfig.LumiaToken,mapping.Lumia,toolStop.Token);toolsStatus+=" · Lumia command sent";}catch{toolsStatus+=" · Lumia command failed. Check token/command.";}}}finally{toolActive--;}}
 void ShowTools(){using(var w=new Form{Text="Streamer.bot & Lumia Stream",Size=new Size(790,700),MinimumSize=new Size(720,650),StartPosition=FormStartPosition.CenterParent,BackColor=Theme.Canvas,ForeColor=Theme.Text,Font=Font}){var panel=new FlowLayoutPanel{Dock=DockStyle.Fill,Padding=new Padding(22),FlowDirection=FlowDirection.TopDown,WrapContents=false,AutoScroll=true};w.Controls.Add(panel);panel.Controls.Add(new Label{Text="Optional automations · Keep these tools on the same computer.\nSamples and replay do not run mapped actions. Each trigger has a 5-second cooldown.",Width=700,Height=58});var bot=new CheckBox{Text="Enable Streamer.bot actions",Checked=toolsConfig.StreamerBot,AutoSize=true};panel.Controls.Add(bot);var port=new NumericUpDown{Minimum=1024,Maximum=65535,Value=Math.Max(1024,Math.Min(65535,toolsConfig.Port)),Width=150};panel.Controls.Add(new Label{Text="WebSocket port",AutoSize=true});panel.Controls.Add(port);var passwordBox=new TextBox{Width=650,UseSystemPasswordChar=true,Text=toolsConfig.Password};panel.Controls.Add(new Label{Text="Streamer.bot WebSocket password",AutoSize=true});panel.Controls.Add(passwordBox);var lumia=new CheckBox{Text="Enable Lumia commands",Checked=toolsConfig.LumiaEnabled,AutoSize=true};panel.Controls.Add(lumia);var token=new TextBox{Width=650,UseSystemPasswordChar=true,Text=toolsConfig.LumiaToken};panel.Controls.Add(new Label{Text="Lumia API token (Settings > API)",AutoSize=true});panel.Controls.Add(token);
 var triggers=new ComboBox{DropDownStyle=ComboBoxStyle.DropDownList,Width=650};triggers.Items.AddRange(new object[]{"Follows","Subscriptions","Resubscriptions","Gift subscriptions","Bits","Tips","Raids","Super Chats and Stickers","Memberships","Kicks and gifts"});foreach(var r in pulse.Rules)if(!triggers.Items.Contains("Pulsoid: "+r.Name))triggers.Items.Add("Pulsoid: "+r.Name);panel.Controls.Add(new Label{Text="When this happens",AutoSize=true});panel.Controls.Add(triggers);var actions=new ComboBox{DropDownStyle=ComboBoxStyle.DropDownList,Width=650};actions.Items.Add(new ToolAction{Id="",Name="No Streamer.bot action"});actions.SelectedIndex=0;panel.Controls.Add(actions);var command=new TextBox{Width=650};panel.Controls.Add(new Label{Text="Lumia command name (blank = no command)",AutoSize=true});panel.Controls.Add(command);var message=new Label{Width=690,Height=55,Text=toolsStatus};
 Action load=delegate{var m=toolsConfig.Mappings.FirstOrDefault(x=>x.Trigger==(string)triggers.SelectedItem);command.Text=m==null?"":m.Lumia;var a=actions.Items.Cast<ToolAction>().FirstOrDefault(x=>x.Id==(m==null?"":m.ActionId));if(a==null){a=new ToolAction{Id=m.ActionId,Name="Saved action · Refresh actions to load its name"};actions.Items.Add(a);}actions.SelectedItem=a;};triggers.SelectedIndexChanged+=delegate{load();};triggers.SelectedIndex=0;
 panel.Controls.Add(Button("Refresh action list",async delegate{try{var data=await ToolWire.Bot((int)port.Value,passwordBox.Text,null,null,toolStop.Token);actions.Items.Clear();actions.Items.Add(new ToolAction{Id="",Name="No Streamer.bot action"});foreach(var item in (Protocol.Items(Protocol.Get(data,"actions"))??new object[0]).Take(2000))if(Protocol.Pick(item,"enabled").Equals("true",StringComparison.OrdinalIgnoreCase))actions.Items.Add(new ToolAction{Id=Protocol.Pick(item,"id"),Name=Protocol.Pick(item,"name")});load();message.Text="Action list loaded. Select an action and save the mapping.";}catch{message.Text="Could not load actions. Check Streamer.bot's WebSocket server, port and password.";}}));
 panel.Controls.Add(Button("Save selected mapping & settings",delegate{var trigger=(string)triggers.SelectedItem;toolsConfig.Mappings.RemoveAll(x=>x.Trigger==trigger);toolsConfig.Mappings.Add(new ToolMapping{Trigger=trigger,ActionId=((ToolAction)actions.SelectedItem).Id,Lumia=command.Text.Trim()});toolsConfig.StreamerBot=bot.Checked;toolsConfig.Port=(int)port.Value;toolsConfig.Password=passwordBox.Text;toolsConfig.LumiaEnabled=lumia.Checked;toolsConfig.LumiaToken=token.Text.Trim();try{AccountStore.Save("integrations",toolsConfig);message.Text="Saved. Real events will use this mapping.";}catch{message.Text="Could not save settings.";}}));panel.Controls.Add(message);w.ShowDialog(this);}}
}

public partial class MainWindow {
 ObsServer controlServer;
 void PublishControls(){if(controlServer!=null)controlServer.Publish(Protocol.Json.Serialize(new{sound=sound.Checked,rules=pulseStop!=null}));}
 void ShowStreamDeck(){using(var w=new Form{Text="Stream Deck",Size=new Size(670,410),StartPosition=FormStartPosition.CenterParent,BackColor=Theme.Canvas,ForeColor=Theme.Text,Font=Font}){var p=new FlowLayoutPanel{Dock=DockStyle.Fill,Padding=new Padding(24),FlowDirection=FlowDirection.TopDown,WrapContents=false};w.Controls.Add(p);p.Controls.Add(new Label{Text="Install the supplied Stream Deck plugin, then add an Assist control key.\nEnter this app's port and pairing token in the key settings.\nThe pairing token controls this app only; keep it private.",Width=610,Height=90});var status=new Label{Width=610,Height=50,Text=controlServer==null?"Controls stopped":"Controls enabled"};p.Controls.Add(status);p.Controls.Add(Button("Enable controls & copy pairing token",delegate{try{if(String.IsNullOrEmpty(toolsConfig.ControlToken)){toolsConfig.ControlToken=Guid.NewGuid().ToString("N")+Guid.NewGuid().ToString("N");AccountStore.Save("integrations",toolsConfig);}if(controlServer==null)controlServer=new ObsServer(ObsPort+3,toolsConfig.ControlToken,name=>BeginInvoke((Action)(()=>{switch(name){case "toggleSound":sound.Checked=!sound.Checked;break;case "pauseRules":StopPulse();break;case "resumeRules":if(pulseStop==null)StartPulse();break;case "replay":if(alerts.Count>0)NotifyDesktop(alerts[0]);break;case "showChat":ShowCombinedChat();break;}})));PublishControls();Clipboard.SetText(toolsConfig.ControlToken);status.Text="Enabled · Port "+(ObsPort+3)+" · Token copied";}catch{status.Text="Could not enable controls. Check another app copy is not running.";}}));p.Controls.Add(Button("Stop controls",delegate{if(controlServer!=null)controlServer.Dispose();controlServer=null;status.Text="Stopped";}));p.Controls.Add(Button("Reset pairing token",delegate{if(controlServer!=null)controlServer.Dispose();controlServer=null;toolsConfig.ControlToken="";AccountStore.Save("integrations",toolsConfig);status.Text="Old pairing token removed. Enable controls to create a new one.";}));w.ShowDialog(this);}}
}
