import vm from 'node:vm';import assert from 'node:assert/strict';import fs from'node:fs';import os from'node:os';import path from'node:path';import {createRequire}from'node:module';
import{PortalStore}from'../src/portal-store.mjs';import{HostAdmin}from'../src/host-admin.mjs';import{hostFeatures}from'../src/host-features.mjs';import{createPortalServer}from'../src/portal-server.mjs';
const require=createRequire(import.meta.url),{JSDOM}=require('../../uc-build-tools/node_modules/jsdom');const dir=fs.mkdtempSync(path.join(os.tmpdir(),'uc-host-dom-'));let registry,server,dom;
try{const config={multi:{maxSessions:3},hostFeatures:{guestInvites:true},recordings:{maxStorageMB:20000,minFreeMB:256}};const store=new PortalStore({directory:dir+'/relay',features:()=>hostFeatures(config)});const host=new HostAdmin({store,config});server=await createPortalServer({config:{bind:'127.0.0.1',port:0},store,status:()=>({state:'ready',width:1920,height:1080,fps:30}),action:async()=>{},changed:()=>{},busy:()=>false,validateDestination:async()=>{},rtmpPort:1935});const origin='http://127.0.0.1:'+server.server.address().port;
 const html=fs.readFileSync(new URL('../DesktopSource/portal.html',import.meta.url),'utf8').replace(/<script[\s\S]*?<\/script>/g,'');dom=new JSDOM(html,{url:origin,runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window,errors=[];w.addEventListener('error',e=>errors.push(e.message));w.confirm=()=>true;w.fetch=(route,options={})=>fetch(new URL(route,origin),{...options,headers:{...options.headers,Origin:origin}});w.AbortSignal=AbortSignal;w.structuredClone=structuredClone;w.matchMedia=()=>({matches:false,addEventListener(){}});w.ResizeObserver=class{observe(){}disconnect(){}};w.HTMLElement.prototype.scrollIntoView=()=>{};w.HTMLCanvasElement.prototype.getContext=()=>null;
 for(const name of ['portal.js','stream-canvas.js','platforms-ui.js','studio-ui.js','release-ui.js','host-ui.js'])vm.runInContext(fs.readFileSync(new URL('../DesktopSource/'+name,import.meta.url),'utf8'),dom.getInternalVMContext(),{filename:name});
 const $=id=>w.document.getElementById(id);const until=async(fn)=>{for(let i=0;i<100;i++){if(fn())return;await new Promise(r=>setTimeout(r,20));}throw Error('DOM wait timed out: '+$('hostFeedback').textContent);};
 $('username').value='owner';$('hostClaimCode').value=fs.readFileSync(dir+'/relay/host-setup-code.txt','utf8').trim();$('hostPanel').querySelector('form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await until(()=>$('host-memberLimit'));assert.equal(host.db.ownerId,'owner');assert.equal($('hostClaimCode').value,'');assert.equal($('host-maxStorageMB').value,'20000');
 assert.equal($('hostLicenseKey'),null);assert(host.canStart('owner'));
 $('host-defaultStorageMB').value='500';$('host-defaultStorageMB').closest('form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await until(()=>host.db.policy.defaultStorageMB===500);await until(()=>!$('hostLoad').disabled);
 store.register('member',store.joinPassword);$('hostLoad').click();await until(()=>$('quota-member'));[...$('hostContent').querySelectorAll('button')].find(b=>b.textContent==='Remove access').click();await until(()=>store.get('member').disabled);await until(()=>$('hostContent').textContent.includes('access removed'));assert.deepEqual(errors,[]);
 // Capture rendered markup for independent inspection without pretending this is visual QA.
 fs.writeFileSync(path.resolve('../rc3-host-panel-rendered.html'),dom.serialize());console.log('PASS DOM + real HTTP: owner claim, free host controls, key clearing, inherited settings, quota save, member removal, and all six application scripts without DOM errors. Visual browser verification is separate.');
}finally{dom?.window.close();await server?.close();fs.rmSync(dir,{recursive:true,force:true});}
