import assert from'node:assert/strict';import path from'node:path';import{createRequire}from'node:module';const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH,headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});
try{const page=await browser.newPage({viewport:{width:1400,height:1100}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{
 window.calls=[];window.failPrepare=true;window.live=false;window.settings={overlays:[],fallback:[]};const custom=[];const account={accounts:{twitch:{id:'a',name:'Alice'},youtube:{id:'y',name:'AliceYT'}},configured:{twitch:true,youtube:true},auth:{},chats:{twitch:{running:false,status:'Stopped'},youtube:{running:false,status:'Stopped'}},messages:[]};
 window.relayDesktop={loadServers:async()=>({schemaVersion:1,selectedKey:'one',servers:[{key:'one',nickname:'Home',id:'alice',token:'x'.repeat(32),address:'http://127.0.0.1:25560'}]}),saveServers:async()=>{},loadLocalProfile:async()=>({displayName:'Bug'}),saveLocalProfile:async()=>{},copy:async()=>{},onPlatforms:()=>{},platform:async(op,input)=>{calls.push({op,input});if(op==='categories')return[{id:'42',name:'Game'}];if(op==='youtube-categories')return[{id:'20',name:'Gaming'},{id:'10',name:'Music'}];if(op==='broadcasts')return[];return account;},studio:async(op,input={})=>{calls.push({op,input});if(op==='custom'){custom.push({id:'custom-one',name:input.name});return{custom};}if(op==='remove-custom'){custom.length=0;return{custom};}if(op==='prepare'&&window.failPrepare){window.failPrepare=false;throw Object.assign(Error('Reconnect Twitch and approve stream-key access, then retry.'),{platform:'twitch',reconnect:true});}if(op==='prepare')return{custom,ready:true,destinations:input.draft.selected.map(id=>({id,name:id})),broadcastId:'broadcast1'};if(op==='metadata')return{results:[{platform:'twitch',ok:true},{platform:'youtube',ok:true}]};if(op==='download')return{saved:true};return{custom,drafts:[]};},request:async q=>{calls.push(q);if(q.route.endsWith('/secrets'))return{obsServer:'rtmp://secret/live',obsKey:'SECRET',loginToken:'x'.repeat(32),destinationBaseUrl:'rtmp://dest/live',destinationStreamKey:'KEY'};if(q.route.endsWith('/recordings'))return{items:[{id:'12345678-1234-1234-1234-123456789abc',title:'Past stream',startedAt:'2026-09-21T00:00:00Z',state:'ended',bytes:12345,downloadable:true}]};if(q.route.endsWith('/settings'))settings=q.body;return{capabilities:{production:1,verifiedProduction:2,streamCanvas:1,recording:true,multipleDestinations:true,pictureInPicture:true,chatOverlays:true,collaboratorFallback:true,registration:true},me:{id:'alice',settings,destinationConfigured:true},status:{state:live?'live':'ready',broadcast:live,held:false,pictureInPicture:true,collabFallback:true,width:1920,height:1080,fps:60},peers:[],requests:[]};}};
 });await page.goto('file://'+new URL('../../DesktopSource/portal.html',import.meta.url).pathname);await page.waitForFunction(()=>document.querySelector('#linkTwitch').textContent.includes('Connected'));
 assert.equal(await page.locator('[data-workspace-tab="twitch"]').count(),0);assert(await page.locator('#connectionsPanel').isVisible());assert(await page.locator('#prepareStream').isDisabled());await page.locator('#linkTwitch').click();assert(await page.locator('#twitchAccount').isVisible());await page.locator('#linkTwitch').click();
 await page.locator('[data-custom-preset="Restream"]').click();await page.locator('#customUrl').fill('rtmp://example.com/live');await page.locator('#customKey').fill('secret-value');await page.locator('#customConnectionForm button[type="submit"], #customConnectionForm button:not([type])').click();assert.equal(await page.locator('#customKey').inputValue(),'');assert(!(await page.locator('body').innerText()).includes('secret-value'));
 await page.locator('#serverConnect').click();await page.locator('#newStream').click();await page.locator('#productionTitle').fill('New session');await page.locator('#productionDescription').fill('Description');await page.locator('#productionDestinations input[value="twitch"]').check();await page.locator('#productionDestinations input[value="youtube"]').check();await page.locator('#productionDestinations input[value="custom-one"]').check();await page.locator('#productionKids').selectOption('no');await page.locator('#productionCategories').click();await page.locator('#productionCategory').selectOption('10');await page.locator('#productionRecord').check();await page.locator('#prepareStream').click();await page.waitForFunction(()=>calls.some(c=>c.op==='prepare'));
 await page.waitForFunction(()=>document.querySelector('#productionActionStatus').textContent.includes('Reconnect Twitch'));
 assert(await page.locator('#reconnectProduction').isVisible());assert(await page.locator('#excludeFailed').isVisible());
 await page.locator('#productionTitle').fill('Edited retry');await page.locator('#prepareStream').click();
 await page.waitForFunction(()=>document.querySelector('#productionActionStatus').textContent.includes('server confirmed'));
 assert(!(await page.locator('#productionRecovery').isVisible()));
 const request=await page.evaluate(()=>calls.find(c=>c.op==='prepare'));assert.equal(request.input.serverKey,'one');assert.deepEqual(request.input.draft.selected,['twitch','youtube','custom-one']);assert.equal(request.input.draft.categoryId,'10');assert(request.input.draft.record);assert(!JSON.stringify(request).includes('secret-value'));
 await page.locator('#productionSync').uncheck();assert(await page.locator('#productionOverrides').isVisible());await page.locator('#productionTwitchTitle').fill('Twitch title');await page.locator('#productionYoutubeTitle').fill('YouTube title');await page.locator('#updateStreamMetadata').click();await page.waitForFunction(()=>calls.some(c=>c.op==='metadata'));assert.equal((await page.evaluate(()=>calls.find(c=>c.op==='metadata'))).input.sync,false);
 await page.locator('#refreshRecordings').click();await page.getByRole('button',{name:'Download',exact:true}).click();assert(await page.evaluate(()=>calls.some(c=>c.op==='download')));
 await page.locator('#editPanels').click();await page.getByRole('button',{name:'Hide Connections panel',exact:true}).click();await page.locator('#addPanel').click();await page.locator('[data-add-panel="connections"]').click();await page.locator('#editPanels').click();
 await page.locator('[data-workspace-tab="social"]').click();assert(await page.locator('#people').isVisible());await page.locator('[data-workspace-tab="combined"]').click();assert(await page.locator('#chatSurface').isVisible());await page.locator('[data-workspace-tab="relay"]').click();
 await page.evaluate(()=>live=true);await page.locator('#refresh').click();assert(await page.locator('#newStream').isDisabled());assert(await page.locator('#prepareStream').isDisabled());assert(await page.locator('#serverSelect').isDisabled());
 await page.setViewportSize({width:500,height:1000});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));assert.deepEqual(errors,[]);await page.screenshot({path:'studio071-mobile.png',fullPage:true});console.log('PASS inline failure/reconnect action, editable retry, verified ready message, Connections offline/login panels, secret masking, custom add, platform selection/category, shared/per-platform titles, prepare/download, editable app panels, Social/chat and active-stream lock.');
}finally{await browser.close();}
